import {
  LayoutDashboard,
  Layers,
  Sparkles,
  FileText,
  PenTool,
  Scissors,
  Factory,
  Boxes,
  Truck,
  Megaphone,
  Store,
  Wallet,
  BarChart3,
  Bot,
  Cpu,
  ShieldCheck,
  MonitorPlay,
  Smartphone,
  Users,
  Brain,
  Radar,
  Zap,
  MapPin,
  Activity,
  Percent,
  Calendar,
  Award,
  LineChart,
  PackageSearch,
  Gauge,
  Banknote,
  Trophy,
  Target,
  KanbanSquare,
  Workflow,
  Ruler,
  ShoppingCart,
  Rocket,
  Star,
  Coins,
  Compass,
  UserCircle2,
  Route as RouteIcon,
  Database,
  ScrollText,
  Lock,
  ArrowLeftRight,
  Leaf,
  Repeat,
  Globe,
  ShieldAlert,
  Tag,
  Send,
  Flame,
  FolderOpen,
  Library,
  type LucideIcon,
} from "lucide-react";

export type ModuleGroup =
  | "Operação"
  | "Coleções"
  | "Desenvolvimento"
  | "PCP & Produção"
  | "Cadeia (PLM)"
  | "Marketing"
  | "Inteligência"
  | "ERP (Integração)"
  | "Plataforma";

export type ModuleSource = "plm" | "erp-mirror";
export type ModuleStatus = "ativo" | "parcial" | "wip";

export type ModuleDef = {
  slug: string;
  path: string;
  title: string;
  short: string;
  description: string;
  icon: LucideIcon;
  group: ModuleGroup;
  source?: ModuleSource; // default: "plm"
  status?: ModuleStatus; // default: "ativo"
  hidden?: boolean; // mantém rota, oculta do menu
};

/** Slugs primários por hub (sempre visíveis na sidebar; demais ficam atrás de "Ver mais"). */
export const PRIMARY_SLUGS = new Set<string>([
  "command-center",
  "fashion-calendar",
  "approvals",
  "colecoes",
  "colecao-360",
  "dev-kanban",
  "produtos",
  "ficha-tecnica",
  "prototipos",
  "materiais",
  "produzir-hoje",
  "produtividade",
  "pcp-kanban",
  "centro-de-corte",
  "lotes",
  "twin-factory",
  "capacity",
  "pcp-stages",
  "terceirizados",
  "war-room-producao",
  "acompanhamento-producao",
  "onde-esta",
  "fornecedores",
  "almoxarifado",
  "mrp",
  "demand-planning",
  "compras",
  "stock-health",
  "marketing",
  "campaigns",
  "influencer-roi",
  "geo-sales",
  "intel-hub",
  "closed-loop",
  "control-tower",
  "product-success",
  "erp-usesoft",
  "erp-integration",
  "sales-performance",
  "margem",
  "equipe",
  "fashion-gpt",
  "bi",
  "security-center",
]);

export const isPrimaryModule = (m: ModuleDef) => PRIMARY_SLUGS.has(m.slug);

/**
 * Reorganização Onda 1 — USE MODA PLM.
 * Nada foi removido: rotas marcadas como ERP-mirror permanecem acessíveis
 * via URL direta; apenas `hidden: true` as retira do sidebar do PLM.
 */
export const MODULES: ModuleDef[] = [
  // === Operação ===
  {
    slug: "command-center",
    path: "/",
    title: "Command Center",
    short: "Painel operacional",
    description: "Coleções, produtos, lotes e gargalos em tempo real.",
    icon: LayoutDashboard,
    group: "Operação",
    status: "parcial",
  },
  {
    slug: "executivo",
    path: "/executivo",
    title: "Executivo",
    short: "Dashboard cruzado",
    description: "Matriz coleção × KPI com semáforo e leitura IA dos vital few.",
    icon: LayoutDashboard,
    group: "Operação",
  },
  {
    slug: "fashion-calendar",
    path: "/fashion-calendar",
    title: "Fashion Calendar",
    short: "Linha do tempo",
    description: "Cronograma de coleções: desenvolvimento, produção e lançamento.",
    icon: Calendar,
    group: "Operação",
  },

  // === Coleções ===
  {
    slug: "colecoes",
    path: "/colecoes",
    title: "Coleções",
    short: "Núcleo do PLM",
    description: "Planejamento, moodboard, tendências, produtos e cronograma.",
    icon: Layers,
    group: "Coleções",
    status: "parcial",
  },
  {
    slug: "colecao-360",
    path: "/colecao-360",
    title: "Coleção 360º",
    short: "Ciclo completo",
    description: "Protótipos → produtos → OPs → vendas → margem em uma tela.",
    icon: Compass,
    group: "Coleções",
  },
  {
    slug: "abc-colecao",
    path: "/abc-colecao",
    title: "Curva ABC por Coleção",
    short: "Pareto de receita",
    description: "Classifica produtos da coleção em A/B/C por receita e aponta cauda e dead stock.",
    icon: BarChart3,
    group: "Coleções",
  },
  {
    slug: "trends",
    path: "/trends",
    title: "Hub de Tendências",
    short: "Moodboard e paleta",
    description: "Referências visuais, paleta e mood do catálogo.",
    icon: Compass,
    group: "Coleções",
  },
  {
    slug: "biblioteca",
    path: "/biblioteca",
    title: "Biblioteca de Referências",
    short: "Catálogo global",
    description: "Acervo navegável de produtos e protótipos com filtros por categoria, estação, cor e coleção. Base para novas referências.",
    icon: Library,
    group: "Coleções",
  },

  // === Desenvolvimento ===
  {
    slug: "dev-kanban",
    path: "/dev-kanban",
    title: "Kanban de Desenvolvimento",
    short: "Pesquisa → liberação",
    description: "Pipeline completo do produto: pesquisa, modelagem, piloto, aprovação.",
    icon: Workflow,
    group: "Desenvolvimento",
  },
  {
    slug: "produtos",
    path: "/produtos",
    title: "Produtos",
    short: "Pipeline de produtos",
    description: "Do briefing à aprovação do estilo.",
    icon: Sparkles,
    group: "Desenvolvimento",
  },
  {
    slug: "variantes",
    path: "/variantes",
    title: "Variantes & SKU",
    short: "Grade cor × tamanho",
    description: "Cores, tamanhos e SKUs gerados por combinação. Base para grade de produção.",
    icon: Tag,
    group: "Desenvolvimento",
  },
  {
    slug: "ficha-tecnica",
    path: "/ficha-tecnica",
    title: "Ficha Técnica",
    short: "Materiais, operações, consumos",
    description:
      "Engenharia de produto: materiais, aviamentos, operações, tempos e custos industriais.",
    icon: FileText,
    group: "Desenvolvimento",
    status: "parcial",
  },
  {
    slug: "cad",
    path: "/cad",
    title: "CAD e Modelagem",
    short: "AI/CDR/DXF/SVG/PDF/PLT",
    description: "Modelagem digital e biblioteca de moldes.",
    icon: PenTool,
    group: "Desenvolvimento",
    status: "parcial",
  },
  {
    slug: "prototipos",
    path: "/prototipos",
    title: "Protótipos",
    short: "Provas e ajustes",
    description: "Ciclo de protótipos, provas e aprovações.",
    icon: Scissors,
    group: "Desenvolvimento",
  },
  {
    slug: "pilots",
    path: "/pilots",
    title: "Pilotos",
    short: "Aprovações de prova",
    description: "Ciclo de pilotos com status próprios e histórico.",
    icon: Ruler,
    group: "Desenvolvimento",
  },
  {
    slug: "materiais",
    path: "/materiais",
    title: "Biblioteca de Materiais",
    short: "Tecidos, aviamentos, cores",
    description: "Materiais reutilizáveis entre coleções (tecidos, aviamentos, paleta de cores).",
    icon: Database,
    group: "Desenvolvimento",
  },
  {
    slug: "fit-sessions",
    path: "/fit-sessions",
    title: "Fit Sessions",
    short: "Provas estruturadas",
    description: "Iterações de prova com comentários por ponto de medida (POM).",
    icon: Ruler,
    group: "Desenvolvimento",
  },
  {
    slug: "target-costing",
    path: "/target-costing",
    title: "Target Costing",
    short: "Custo alvo × real",
    description: "Meta de custo e margem por produto comparada ao custo real da ficha técnica.",
    icon: Target,
    group: "Desenvolvimento",
  },
  {
    slug: "sourcing",
    path: "/sourcing",
    title: "Sourcing & RFQ",
    short: "Cotação de materiais",
    description: "Cotações de material em múltiplos fornecedores com comparação lado a lado.",
    icon: ShoppingCart,
    group: "Cadeia (PLM)",
  },
  {
    slug: "sustentabilidade",
    path: "/sustentabilidade",
    title: "Sustainability Scoring",
    short: "CO₂, % reciclado, cert.",
    description:
      "Score sustentável por produto: pegada CO₂, água, reciclado, orgânico e certificações.",
    icon: Leaf,
    group: "Plataforma",
    hidden: true,
  },

  // === PCP & Produção ===
  {
    slug: "pcp",
    path: "/pcp",
    title: "PCP e Produção",
    short: "Ordens e capacidade",
    description: "Planejamento, ordens de produção e apontamento.",
    icon: Factory,
    group: "PCP & Produção",
    hidden: true,
  },
  {
    slug: "produzir-hoje",
    path: "/produzir-hoje",
    title: "Produzir Hoje",
    short: "Operação sem filtros",
    description: "Top 3 OPs por setor, ordenadas por prioridade e prazo. Operador abre e trabalha.",
    icon: Flame,
    group: "Operação",
  },
  {
    slug: "produtividade",
    path: "/produtividade",
    title: "Produtividade",
    short: "Ranking 7 dias",
    description: "Quem mais passou peças hoje e na semana, por setor.",
    icon: Activity,
    group: "Operação",
  },
  {
    slug: "pcp-kanban",
    path: "/pcp-kanban",
    title: "PCP Kanban",
    short: "Board por OP ou lote",
    description:
      "Mova OPs entre setores, agrupe por lote e veja gargalos antes de atrasarem a entrega.",
    icon: KanbanSquare,
    group: "PCP & Produção",
    status: "parcial",
  },
  {
    slug: "centro-de-corte",
    path: "/centro-de-corte",
    title: "Centro de Corte",
    short: "Corte, enfesto e liberação",
    description:
      "Priorize enfestos, acompanhe peças cortadas e libere OPs para costura com menos retrabalho.",
    icon: Scissors,
    group: "PCP & Produção",
  },
  {
    slug: "lotes",
    path: "/lotes",
    title: "Lotes & Rastreabilidade",
    short: "Batch tracking",
    description:
      "Lotes com OPs vinculadas, % completo, passagens, ocorrências e histórico por estágio.",
    icon: Boxes,
    group: "PCP & Produção",
  },
  {
    slug: "twin-factory",
    path: "/twin-factory",
    title: "Torre de Controle",
    short: "Twin Factory",
    description:
      "Visão em tempo real de setores, lotes ativos, passagens do dia e gargalos por fila.",
    icon: Activity,
    group: "PCP & Produção",
  },
  {
    slug: "capacity",
    path: "/capacity",
    title: "Capacidade de Produção",
    short: "OEE, carga e risco",
    description: "Carga por fornecedor/facção, WIP, atrasos, OEE e indicação de sobrecarga.",
    icon: Gauge,
    group: "PCP & Produção",
  },
  {
    slug: "pcp-stages",
    path: "/pcp-stages",
    title: "Etapas do PCP",
    short: "Configurar estágios",
    description: "Configure os setores que alimentam Kanban, Torre de Controle e rastreabilidade.",
    icon: KanbanSquare,
    group: "PCP & Produção",
  },
  {
    slug: "product-routing",
    path: "/product-routing",
    title: "Roteiro Produtivo (BOP)",
    short: "Sequência por produto",
    description:
      "Defina o roteiro de estágios por produto ou família. Jeans usa lavanderia, malha pula — o Kanban respeita esse roteiro.",
    icon: RouteIcon,
    group: "PCP & Produção",
  },
  {
    slug: "terceirizados",
    path: "/terceirizados",
    title: "Terceirizados",
    short: "Peças em facções",
    description:
      "Peças, lotes, referências, 2ª linha e tempo em poder de cada facção, em tempo real.",
    icon: Truck,
    group: "PCP & Produção",
  },

  // === Cadeia (PLM) — insumos / fornecedores ===
  {
    slug: "almoxarifado",
    path: "/almoxarifado",
    title: "Almoxarifado (Insumos)",
    short: "Tecidos e aviamentos",
    description: "Controle técnico de insumos da produção.",
    icon: Boxes,
    group: "Cadeia (PLM)",
  },
  {
    slug: "cadeia-360",
    path: "/cadeia-360",
    title: "Cadeia 360º",
    short: "Portal + sourcing + capacidade",
    description: "Portal do fornecedor, sourcing inteligente e calendário de capacidade.",
    icon: Truck,
    group: "Cadeia (PLM)",
  },
  {
    slug: "fornecedores",
    path: "/fornecedores",
    title: "Fornecedores",
    short: "Portal de parceiros",
    description: "Portal de fornecedores e facções.",
    icon: Truck,
    group: "Cadeia (PLM)",
  },
  {
    slug: "supplier-score",
    path: "/supplier-score",
    title: "Supplier Scorecard",
    short: "OTD e rating",
    description: "Score 0–100 por fornecedor com OTD, rating e tiers.",
    icon: Trophy,
    group: "Cadeia (PLM)",
  },
  {
    slug: "stock-health",
    path: "/stock-health",
    title: "Saúde de Insumos",
    short: "Cobertura técnica",
    description: "Ruptura, baixo, excesso e cobertura — escopo insumos PLM.",
    icon: PackageSearch,
    group: "Cadeia (PLM)",
    status: "parcial",
  },
  {
    slug: "compras",
    path: "/compras",
    title: "Necessidade de Compra",
    short: "Sugestão técnica",
    description: "Necessidade técnica de insumos (sem financeiro — envia para o ERP).",
    icon: ShoppingCart,
    group: "Cadeia (PLM)",
    status: "parcial",
  },
  {
    slug: "mrp",
    path: "/mrp",
    title: "MRP Inteligente",
    short: "Mín · Máx · LEC · PP",
    description:
      "Estoque mínimo/máximo, LEC, ponto de pedido e sugestão automática de compras com nível de serviço por material.",
    icon: Gauge,
    group: "Cadeia (PLM)",
  },
  {
    slug: "mrp-executivo",
    path: "/mrp/executivo",
    title: "MRP Executivo",
    short: "Leitura IA do MRP",
    description: "Visão executiva do MRP com cobertura, capital empatado e copiloto IA.",
    icon: Brain,
    group: "Cadeia (PLM)",
  },
  {
    slug: "mrp-bi",
    path: "/mrp/bi",
    title: "MRP · BI",
    short: "Curva ABC/XYZ",
    description: "Inteligência analítica do MRP: ABC/XYZ, giro, ruptura e excesso por categoria.",
    icon: BarChart3,
    group: "Cadeia (PLM)",
  },
  {
    slug: "demand-planning",
    path: "/demand-planning",
    title: "Demand Planning",
    short: "Grade × ABC × Sazonalidade",
    description:
      "Sugestão de compras por fornecedor em matriz cor × tamanho, com Z dinâmico por classe ABC e sazonalidade mensal.",
    icon: Sparkles,
    group: "Cadeia (PLM)",
  },
  {
    slug: "faccoes",
    path: "/faccoes",
    title: "Facção 360°",
    short: "Perda, defeito, lead time",
    description:
      "Painel consolidado das oficinas externas — OS abertas, atrasadas, índice de perda/defeito e lead time real (90 dias).",
    icon: Factory,
    group: "Cadeia (PLM)",
  },
  {
    slug: "time-and-action",
    path: "/time-and-action",
    title: "Time & Action",
    short: "Cronograma de coleção",
    description:
      "Cronograma de desenvolvimento da coleção do briefing ao lançamento, com SLA por etapa e desvio real × planejado.",
    icon: CalendarClock,
    group: "Desenvolvimento (PLM)",
  },

  // === Marketing (de produto) ===
  {
    slug: "marketing",
    path: "/marketing",
    title: "Marketing de Produto",
    short: "Performance por produto",
    description: "Performance por produto, coleção e região (lê do ERP).",
    icon: Megaphone,
    group: "Marketing",
    status: "parcial",
  },
  {
    slug: "influencers",
    path: "/influencers",
    title: "Influenciadores",
    short: "Cadastro e envios",
    description: "Cadastro, produtos enviados e baseline antes/depois.",
    icon: UserCircle2,
    group: "Marketing",
    status: "parcial",
  },
  {
    slug: "marketing-envios",
    path: "/marketing-envios",
    title: "Envios para Influencers",
    short: "Coleção → influencer",
    description: "Controle de envios por coleção, sugestões IA e uplift de vendas.",
    icon: Send,
    group: "Marketing",
  },
  {
    slug: "influencer-roi",
    path: "/influencer-roi",
    title: "ROI de Influencers",
    short: "Uplift e ROAS",
    description: "Crescimento de vendas/pedidos após postagem (dados ERP).",
    icon: Award,
    group: "Marketing",
    status: "parcial",
  },
  {
    slug: "campaigns",
    path: "/campaigns",
    title: "Campanhas",
    short: "Performance por canal",
    description: "Investimento, receita atribuída e ROAS por campanha.",
    icon: Target,
    group: "Marketing",
  },
  {
    slug: "geo-sales",
    path: "/geo-sales",
    title: "Geo Sales",
    short: "Mapa do Brasil",
    description: "Aceitação por UF e região (dados do ERP).",
    icon: MapPin,
    group: "Marketing",
    status: "parcial",
  },

  // === Inteligência ===
  {
    slug: "intel-hub",
    path: "/intel-hub",
    title: "Inteligência Operacional",
    short: "Hub unificado",
    description: "Alertas, reposição técnica e scores em uma tela única.",
    icon: Brain,
    group: "Inteligência",
  },
  {
    slug: "closed-loop",
    path: "/closed-loop",
    title: "PLM Closed-Loop",
    short: "Voz do cliente → próxima coleção",
    description: "Reviews, NPS, ABC/lifecycle e replanejamento (repetir/repaginar/cortar).",
    icon: Repeat,
    group: "Inteligência",
  },
  {
    slug: "omnichannel",
    path: "/omnichannel",
    title: "Omnichannel & Marketplace",
    short: "Mix de canais",
    description: "Receita por canal D2C/B2B/marketplace, ticket médio e geografia.",
    icon: Globe,
    group: "Marketing",
  },
  {
    slug: "fpa",
    path: "/fpa",
    title: "Planejamento Financeiro (ERP)",
    short: "Pertence ao ERP",
    description: "FP&A e orçamento são do ERP — rota preservada para histórico.",
    icon: Banknote,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },
  {
    slug: "quality",
    path: "/quality",
    title: "Centro de Qualidade & SLA",
    short: "OTD e defeitos",
    description: "Inspeções, taxa de defeito por fornecedor e cumprimento de prazo.",
    icon: ShieldAlert,
    group: "Cadeia (PLM)",
  },
  {
    slug: "inspecoes",
    path: "/inspecoes",
    title: "Inspeções AQL",
    short: "Laudos por OP/OS",
    description: "Plano AQL, defeitos críticos/maiores/menores e resultado da inspeção.",
    icon: ShieldAlert,
    group: "Cadeia (PLM)",
  },
  {
    slug: "intelligence",
    path: "/intelligence",
    title: "Intelligence Engine",
    short: "Inteligência operacional",
    description: "O que produzir, repor, atrasar — sinais operacionais.",
    icon: Brain,
    group: "Inteligência",
  },
  {
    slug: "control-tower",
    path: "/control-tower",
    title: "Control Tower",
    short: "Demand & Supply",
    description: "Necessidade por grade com semáforo de cobertura.",
    icon: Radar,
    group: "Inteligência",
  },
  {
    slug: "product-score",
    path: "/product-score",
    title: "Product Score",
    short: "Pontuação 0–100",
    description: "Pontuação por vendas, margem, ROI e giro.",
    icon: Star,
    group: "Inteligência",
  },
  {
    slug: "product-success",
    path: "/product-success",
    title: "Product Success",
    short: "Score preditivo",
    description: "Probabilidade de sucesso por produto.",
    icon: Rocket,
    group: "Inteligência",
  },
  {
    slug: "grade-needs",
    path: "/grade-needs",
    title: "Necessidade por Grade",
    short: "Quebra PP/P/M/G/GG",
    description: "Distribuição sugerida por tamanho.",
    icon: Ruler,
    group: "Inteligência",
  },
  {
    slug: "replenishment",
    path: "/replenishment",
    title: "Sugestão de Reposição",
    short: "Sinal p/ produção",
    description: "Sinal técnico de reposição p/ PCP (sem compras financeiras).",
    icon: Zap,
    group: "Inteligência",
    status: "parcial",
  },
  {
    slug: "war-room-producao",
    path: "/war-room-producao",
    title: "Sala de Guerra · Produção",
    short: "Visão única do dia",
    description:
      "Heatmap de etapas, OPs críticas, terceirizados e plano de ação do Coordenador PCP.",
    icon: Factory,
    group: "PCP & Produção",
  },
  {
    slug: "acompanhamento-producao",
    path: "/acompanhamento-producao",
    title: "Acompanhamento de Produção",
    short: "Kanban macro + micro",
    description:
      "Onde está cada lote agora — kanban por setor (interno/externo), KPIs, resumo por terceiro, histórico de passagens e exportação.",
    icon: Factory,
    group: "PCP & Produção",
  },

  {
    slug: "onde-esta",
    path: "/onde-esta",
    title: "Onde está?",
    short: "Rastreabilidade visual",
    description:
      "Busque uma OP ou lote e veja etapa atual, tempo parado, facção e timeline de passagens.",
    icon: MapPin,
    group: "PCP & Produção",
  },

  // === ERP (Integração) — leitura/espelho ===
  {
    slug: "erp-usesoft",
    path: "/erp-usesoft",
    title: "ERP Usesoft · Live",
    short: "Leitura ao vivo",
    description:
      "Coleções (grifes), produtos, estoque, vendas, compras, clientes e fornecedores lidos diretamente do banco do Usesoft — read-only.",
    icon: Database,
    group: "ERP (Integração)",
    source: "erp-mirror",
  },
  {
    slug: "erp-integration",
    path: "/erp-integration",
    title: "Integração ERP",
    short: "Webhook + releases",
    description:
      "Endpoint HMAC para receber vendas/compras/estoque do ERP e enviar releases do PLM.",
    icon: Workflow,
    group: "ERP (Integração)",
  },
  {
    slug: "attribution",
    path: "/attribution",
    title: "Marketing Attribution (ERP)",
    short: "Leitura ERP",
    description: "Receita atribuída por canal — espelho do ERP.",
    icon: RouteIcon,
    group: "ERP (Integração)",
    source: "erp-mirror",
    status: "parcial",
  },
  {
    slug: "sales-performance",
    path: "/sales-performance",
    title: "Sales Performance (ERP)",
    short: "Leitura ERP",
    description: "Receita, canais, ticket médio e top SKUs — espelho do ERP.",
    icon: LineChart,
    group: "ERP (Integração)",
    source: "erp-mirror",
    status: "parcial",
  },
  {
    slug: "margem",
    path: "/margem",
    title: "Margem & Rentabilidade (ERP)",
    short: "Leitura ERP",
    description: "Margem real por SKU — espelho do ERP.",
    icon: Percent,
    group: "ERP (Integração)",
    source: "erp-mirror",
    status: "parcial",
  },
  {
    slug: "profitability",
    path: "/profitability",
    title: "Rentabilidade por Coleção (ERP)",
    short: "Leitura ERP",
    description: "Lucro real por coleção — espelho do ERP.",
    icon: Coins,
    group: "ERP (Integração)",
    source: "erp-mirror",
    status: "parcial",
  },

  // Módulos ERP-mirror operacionais — rotas mantidas, ocultas do menu PLM
  {
    slug: "financeiro",
    path: "/financeiro",
    title: "Financeiro (ERP)",
    short: "Pertence ao ERP",
    description: "Operado no ERP — rota preservada para histórico.",
    icon: Wallet,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },
  {
    slug: "cashflow",
    path: "/cashflow",
    title: "Cashflow (ERP)",
    short: "Pertence ao ERP",
    description: "Operado no ERP — rota preservada para histórico.",
    icon: Banknote,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },
  {
    slug: "comercial",
    path: "/comercial",
    title: "Comercial / B2B (ERP)",
    short: "Pertence ao ERP",
    description: "Operado no ERP — rota preservada para histórico.",
    icon: Store,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },
  {
    slug: "clientes",
    path: "/clientes",
    title: "Clientes (ERP)",
    short: "Pertence ao ERP",
    description: "Cadastro fica no ERP — rota preservada para histórico.",
    icon: Users,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },
  {
    slug: "representantes",
    path: "/representantes",
    title: "Representantes (ERP)",
    short: "Pertence ao ERP",
    description: "Cadastro fica no ERP — rota preservada para histórico.",
    icon: UserCircle2,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },
  {
    slug: "pedidos-compra",
    path: "/pedidos-compra",
    title: "Pedidos de Compra (ERP)",
    short: "Pertence ao ERP",
    description: "Compras financeiras ficam no ERP — rota preservada para histórico.",
    icon: ShoppingCart,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },
  {
    slug: "movimentacoes",
    path: "/movimentacoes",
    title: "Movimentações Estoque (ERP)",
    short: "Pertence ao ERP",
    description: "Estoque fiscal fica no ERP — rota preservada para histórico.",
    icon: ArrowLeftRight,
    group: "ERP (Integração)",
    source: "erp-mirror",
    hidden: true,
  },

  // === Plataforma ===
  {
    slug: "dpp",
    path: "/dpp",
    title: "Digital Product Passport",
    short: "Rastreabilidade",
    description: "Passaporte digital e compliance ESG.",
    icon: ShieldCheck,
    group: "Plataforma",
    hidden: true,
  },
  {
    slug: "sustentabilidade-360",
    path: "/sustentabilidade-360",
    title: "Sustentabilidade 360º",
    short: "ESG por coleção",
    description: "Pegada CO₂, materiais sustentáveis, certificações e rastreabilidade DPP.",
    icon: Leaf,
    group: "Plataforma",
    hidden: true,
  },
  {
    slug: "designer-workspace",
    path: "/designer-workspace",
    title: "Workspace do Designer",
    short: "Tudo no seu nome",
    description: "Protótipos abertos, aprovações pendentes e atalhos de criação.",
    icon: PenTool,
    group: "Desenvolvimento",
  },
  {
    slug: "approvals",
    path: "/approvals",
    title: "Workflow de Aprovações",
    short: "Gates do PLM",
    description: "Coleção → ficha técnica → piloto → liberação para produção.",
    icon: Workflow,
    group: "Operação",
  },
  {
    slug: "showroom",
    path: "/showroom",
    title: "Showroom Digital",
    short: "Vitrine 3D",
    description: "Showroom virtual com lookbooks interativos.",
    icon: MonitorPlay,
    group: "Plataforma",
    status: "wip",
  },
  {
    slug: "mobile",
    path: "/mobile",
    title: "Aplicativo Mobile",
    short: "App para times",
    description: "App nativo para campo, fábrica e vendedores.",
    icon: Smartphone,
    group: "Plataforma",
    status: "wip",
    hidden: true,
  },
  {
    slug: "bi",
    path: "/bi",
    title: "BI e Analytics",
    short: "Insights e KPIs",
    description: "Dashboards customizáveis.",
    icon: BarChart3,
    group: "Operação",
  },
  {
    slug: "fashion-gpt",
    path: "/fashion-gpt",
    title: "Fashion GPT",
    short: "Copiloto de moda",
    description: "Assistente especialista no seu negócio de moda.",
    icon: Bot,
    group: "Operação",
  },
  {
    slug: "use-ai",
    path: "/use-ai",
    title: "USE AI",
    short: "Automação inteligente",
    description: "Agentes de IA para automação.",
    icon: Cpu,
    group: "Operação",
  },
  {
    slug: "security-center",
    path: "/security-center",
    title: "Segurança",
    short: "MFA, LGPD, backup",
    description: "MFA TOTP, política de senhas, criptografia e backups.",
    icon: Lock,
    group: "Plataforma",
  },
  {
    slug: "audit",
    path: "/audit",
    title: "Auditoria & LGPD",
    short: "Logs e rastreabilidade",
    description: "Eventos auditáveis com filtro por entidade/ação.",
    icon: ScrollText,
    group: "Plataforma",
  },
  {
    slug: "timeline",
    path: "/timeline",
    title: "Timeline Global",
    short: "Tudo o que aconteceu",
    description: "Feed cronológico unificado: auditoria, estágios, ocorrências, qualidade, protótipos e marketing.",
    icon: Activity,
    group: "Plataforma",
  },
  {
    slug: "documentos",
    path: "/documentos",
    title: "Central de Documentos",
    short: "Tudo num só lugar",
    description:
      "Fichas técnicas, anexos do portal de fornecedor, capas de coleção, moodboards e fotos de produto — filtrável e pesquisável.",
    icon: FolderOpen,
    group: "Plataforma",
  },
  {
    slug: "copilot",
    path: "/copilot",
    title: "Copiloto PCP",
    short: "Chat com seus dados",
    description:
      "Pergunte sobre OPs atrasadas, riscos, faltas de insumo, ocorrências críticas e fornecedores — IA consulta os dados reais via tools.",
    icon: Bot,
    group: "Inteligência",
  },
  {
    slug: "data-lake",
    path: "/data-lake",
    title: "Data Lake",
    short: "Camada unificada",
    description: "Visão consolidada de todos os domínios.",
    icon: Database,
    group: "Plataforma",
    hidden: true,
  },
  {
    slug: "equipe",
    path: "/equipe",
    title: "Equipe & Permissões",
    short: "Usuários e papéis",
    description: "Gerencie usuários e atribua papéis (admin).",
    icon: Users,
    group: "Plataforma",
  },
];

export const MODULE_GROUPS: ModuleGroup[] = [
  "Operação",
  "Coleções",
  "Desenvolvimento",
  "PCP & Produção",
  "Cadeia (PLM)",
  "Marketing",
  "Inteligência",
  "ERP (Integração)",
  "Plataforma",
];

export type AppSector = "marketing" | "pcp" | "desenvolvimento";
export const APP_SECTORS: AppSector[] = ["marketing", "pcp", "desenvolvimento"];
export const SECTOR_LABEL: Record<AppSector, string> = {
  marketing: "Marketing",
  pcp: "PCP",
  desenvolvimento: "Desenvolvimento",
};

/** Mapa grupo → setor exigido. Grupos ausentes são livres (visíveis a todos).
 *  Marketing/Influencers liberados a todos: são telas de inteligência (leitura),
 *  não operam dados sensíveis — voltam a aparecer no menu para qualquer usuário. */
export const GROUP_SECTOR: Partial<Record<ModuleGroup, AppSector>> = {
  Desenvolvimento: "desenvolvimento",
};

export function moduleSector(m: ModuleDef): AppSector | null {
  return GROUP_SECTOR[m.group] ?? null;
}

export function moduleAllowed(m: ModuleDef, userSectors: AppSector[], isAdmin: boolean): boolean {
  if (isAdmin) return true;
  const required = moduleSector(m);
  if (!required) return true;
  return userSectors.includes(required);
}
