/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DppIdRouteImport } from './routes/dpp.$id'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app.index'
import { Route as AuthenticatedAppUseAiRouteImport } from './routes/_authenticated/_app.use-ai'
import { Route as AuthenticatedAppTwinFactoryRouteImport } from './routes/_authenticated/_app.twin-factory'
import { Route as AuthenticatedAppTrendsRouteImport } from './routes/_authenticated/_app.trends'
import { Route as AuthenticatedAppSupplierScoreRouteImport } from './routes/_authenticated/_app.supplier-score'
import { Route as AuthenticatedAppStockHealthRouteImport } from './routes/_authenticated/_app.stock-health'
import { Route as AuthenticatedAppShowroomRouteImport } from './routes/_authenticated/_app.showroom'
import { Route as AuthenticatedAppSecurityCenterRouteImport } from './routes/_authenticated/_app.security-center'
import { Route as AuthenticatedAppSalesPerformanceRouteImport } from './routes/_authenticated/_app.sales-performance'
import { Route as AuthenticatedAppRepresentantesRouteImport } from './routes/_authenticated/_app.representantes'
import { Route as AuthenticatedAppReplenishmentRouteImport } from './routes/_authenticated/_app.replenishment'
import { Route as AuthenticatedAppPrototiposRouteImport } from './routes/_authenticated/_app.prototipos'
import { Route as AuthenticatedAppProfitabilityRouteImport } from './routes/_authenticated/_app.profitability'
import { Route as AuthenticatedAppProdutosRouteImport } from './routes/_authenticated/_app.produtos'
import { Route as AuthenticatedAppProductSuccessRouteImport } from './routes/_authenticated/_app.product-success'
import { Route as AuthenticatedAppProductScoreRouteImport } from './routes/_authenticated/_app.product-score'
import { Route as AuthenticatedAppPilotsRouteImport } from './routes/_authenticated/_app.pilots'
import { Route as AuthenticatedAppPedidosCompraRouteImport } from './routes/_authenticated/_app.pedidos-compra'
import { Route as AuthenticatedAppPcpKanbanRouteImport } from './routes/_authenticated/_app.pcp-kanban'
import { Route as AuthenticatedAppPcpRouteImport } from './routes/_authenticated/_app.pcp'
import { Route as AuthenticatedAppMovimentacoesRouteImport } from './routes/_authenticated/_app.movimentacoes'
import { Route as AuthenticatedAppMobileRouteImport } from './routes/_authenticated/_app.mobile'
import { Route as AuthenticatedAppMarketingRouteImport } from './routes/_authenticated/_app.marketing'
import { Route as AuthenticatedAppMargemRouteImport } from './routes/_authenticated/_app.margem'
import { Route as AuthenticatedAppIntelligenceRouteImport } from './routes/_authenticated/_app.intelligence'
import { Route as AuthenticatedAppInfluencersRouteImport } from './routes/_authenticated/_app.influencers'
import { Route as AuthenticatedAppInfluencerRoiRouteImport } from './routes/_authenticated/_app.influencer-roi'
import { Route as AuthenticatedAppGradeNeedsRouteImport } from './routes/_authenticated/_app.grade-needs'
import { Route as AuthenticatedAppGeoSalesRouteImport } from './routes/_authenticated/_app.geo-sales'
import { Route as AuthenticatedAppFornecedoresRouteImport } from './routes/_authenticated/_app.fornecedores'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/_app.financeiro'
import { Route as AuthenticatedAppFichaTecnicaRouteImport } from './routes/_authenticated/_app.ficha-tecnica'
import { Route as AuthenticatedAppFashionGptRouteImport } from './routes/_authenticated/_app.fashion-gpt'
import { Route as AuthenticatedAppFashionCalendarRouteImport } from './routes/_authenticated/_app.fashion-calendar'
import { Route as AuthenticatedAppEquipeRouteImport } from './routes/_authenticated/_app.equipe'
import { Route as AuthenticatedAppDppRouteImport } from './routes/_authenticated/_app.dpp'
import { Route as AuthenticatedAppDevKanbanRouteImport } from './routes/_authenticated/_app.dev-kanban'
import { Route as AuthenticatedAppDataLakeRouteImport } from './routes/_authenticated/_app.data-lake'
import { Route as AuthenticatedAppControlTowerRouteImport } from './routes/_authenticated/_app.control-tower'
import { Route as AuthenticatedAppComprasRouteImport } from './routes/_authenticated/_app.compras'
import { Route as AuthenticatedAppComercialRouteImport } from './routes/_authenticated/_app.comercial'
import { Route as AuthenticatedAppColecoesRouteImport } from './routes/_authenticated/_app.colecoes'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/_app.clientes'
import { Route as AuthenticatedAppCentroDeCorteRouteImport } from './routes/_authenticated/_app.centro-de-corte'
import { Route as AuthenticatedAppCashflowRouteImport } from './routes/_authenticated/_app.cashflow'
import { Route as AuthenticatedAppCapacityRouteImport } from './routes/_authenticated/_app.capacity'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/_app.campaigns'
import { Route as AuthenticatedAppCadRouteImport } from './routes/_authenticated/_app.cad'
import { Route as AuthenticatedAppBiRouteImport } from './routes/_authenticated/_app.bi'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/_app.audit'
import { Route as AuthenticatedAppAttributionRouteImport } from './routes/_authenticated/_app.attribution'
import { Route as AuthenticatedAppAlmoxarifadoRouteImport } from './routes/_authenticated/_app.almoxarifado'
import { Route as ApiPublicAgentsRunDueRouteImport } from './routes/api.public.agents.run-due'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DppIdRoute = DppIdRouteImport.update({
  id: '/dpp/$id',
  path: '/dpp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUseAiRoute = AuthenticatedAppUseAiRouteImport.update({
  id: '/use-ai',
  path: '/use-ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTwinFactoryRoute =
  AuthenticatedAppTwinFactoryRouteImport.update({
    id: '/twin-factory',
    path: '/twin-factory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrendsRoute = AuthenticatedAppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSupplierScoreRoute =
  AuthenticatedAppSupplierScoreRouteImport.update({
    id: '/supplier-score',
    path: '/supplier-score',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStockHealthRoute =
  AuthenticatedAppStockHealthRouteImport.update({
    id: '/stock-health',
    path: '/stock-health',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppShowroomRoute =
  AuthenticatedAppShowroomRouteImport.update({
    id: '/showroom',
    path: '/showroom',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSecurityCenterRoute =
  AuthenticatedAppSecurityCenterRouteImport.update({
    id: '/security-center',
    path: '/security-center',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSalesPerformanceRoute =
  AuthenticatedAppSalesPerformanceRouteImport.update({
    id: '/sales-performance',
    path: '/sales-performance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRepresentantesRoute =
  AuthenticatedAppRepresentantesRouteImport.update({
    id: '/representantes',
    path: '/representantes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReplenishmentRoute =
  AuthenticatedAppReplenishmentRouteImport.update({
    id: '/replenishment',
    path: '/replenishment',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrototiposRoute =
  AuthenticatedAppPrototiposRouteImport.update({
    id: '/prototipos',
    path: '/prototipos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfitabilityRoute =
  AuthenticatedAppProfitabilityRouteImport.update({
    id: '/profitability',
    path: '/profitability',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProdutosRoute =
  AuthenticatedAppProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductSuccessRoute =
  AuthenticatedAppProductSuccessRouteImport.update({
    id: '/product-success',
    path: '/product-success',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductScoreRoute =
  AuthenticatedAppProductScoreRouteImport.update({
    id: '/product-score',
    path: '/product-score',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPilotsRoute = AuthenticatedAppPilotsRouteImport.update({
  id: '/pilots',
  path: '/pilots',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPedidosCompraRoute =
  AuthenticatedAppPedidosCompraRouteImport.update({
    id: '/pedidos-compra',
    path: '/pedidos-compra',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPcpKanbanRoute =
  AuthenticatedAppPcpKanbanRouteImport.update({
    id: '/pcp-kanban',
    path: '/pcp-kanban',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPcpRoute = AuthenticatedAppPcpRouteImport.update({
  id: '/pcp',
  path: '/pcp',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMovimentacoesRoute =
  AuthenticatedAppMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMobileRoute = AuthenticatedAppMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMarketingRoute =
  AuthenticatedAppMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMargemRoute = AuthenticatedAppMargemRouteImport.update({
  id: '/margem',
  path: '/margem',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntelligenceRoute =
  AuthenticatedAppIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInfluencersRoute =
  AuthenticatedAppInfluencersRouteImport.update({
    id: '/influencers',
    path: '/influencers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInfluencerRoiRoute =
  AuthenticatedAppInfluencerRoiRouteImport.update({
    id: '/influencer-roi',
    path: '/influencer-roi',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGradeNeedsRoute =
  AuthenticatedAppGradeNeedsRouteImport.update({
    id: '/grade-needs',
    path: '/grade-needs',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGeoSalesRoute =
  AuthenticatedAppGeoSalesRouteImport.update({
    id: '/geo-sales',
    path: '/geo-sales',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFornecedoresRoute =
  AuthenticatedAppFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFichaTecnicaRoute =
  AuthenticatedAppFichaTecnicaRouteImport.update({
    id: '/ficha-tecnica',
    path: '/ficha-tecnica',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFashionGptRoute =
  AuthenticatedAppFashionGptRouteImport.update({
    id: '/fashion-gpt',
    path: '/fashion-gpt',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFashionCalendarRoute =
  AuthenticatedAppFashionCalendarRouteImport.update({
    id: '/fashion-calendar',
    path: '/fashion-calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEquipeRoute = AuthenticatedAppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDppRoute = AuthenticatedAppDppRouteImport.update({
  id: '/dpp',
  path: '/dpp',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDevKanbanRoute =
  AuthenticatedAppDevKanbanRouteImport.update({
    id: '/dev-kanban',
    path: '/dev-kanban',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDataLakeRoute =
  AuthenticatedAppDataLakeRouteImport.update({
    id: '/data-lake',
    path: '/data-lake',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppControlTowerRoute =
  AuthenticatedAppControlTowerRouteImport.update({
    id: '/control-tower',
    path: '/control-tower',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComprasRoute = AuthenticatedAppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComercialRoute =
  AuthenticatedAppComercialRouteImport.update({
    id: '/comercial',
    path: '/comercial',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppColecoesRoute =
  AuthenticatedAppColecoesRouteImport.update({
    id: '/colecoes',
    path: '/colecoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCentroDeCorteRoute =
  AuthenticatedAppCentroDeCorteRouteImport.update({
    id: '/centro-de-corte',
    path: '/centro-de-corte',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCashflowRoute =
  AuthenticatedAppCashflowRouteImport.update({
    id: '/cashflow',
    path: '/cashflow',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCapacityRoute =
  AuthenticatedAppCapacityRouteImport.update({
    id: '/capacity',
    path: '/capacity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCadRoute = AuthenticatedAppCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBiRoute = AuthenticatedAppBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAttributionRoute =
  AuthenticatedAppAttributionRouteImport.update({
    id: '/attribution',
    path: '/attribution',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlmoxarifadoRoute =
  AuthenticatedAppAlmoxarifadoRouteImport.update({
    id: '/almoxarifado',
    path: '/almoxarifado',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicAgentsRunDueRoute = ApiPublicAgentsRunDueRouteImport.update({
  id: '/api/public/agents/run-due',
  path: '/api/public/agents/run-due',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/dpp/$id': typeof DppIdRoute
  '/almoxarifado': typeof AuthenticatedAppAlmoxarifadoRoute
  '/attribution': typeof AuthenticatedAppAttributionRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/bi': typeof AuthenticatedAppBiRoute
  '/cad': typeof AuthenticatedAppCadRoute
  '/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/capacity': typeof AuthenticatedAppCapacityRoute
  '/cashflow': typeof AuthenticatedAppCashflowRoute
  '/centro-de-corte': typeof AuthenticatedAppCentroDeCorteRoute
  '/clientes': typeof AuthenticatedAppClientesRoute
  '/colecoes': typeof AuthenticatedAppColecoesRoute
  '/comercial': typeof AuthenticatedAppComercialRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/control-tower': typeof AuthenticatedAppControlTowerRoute
  '/data-lake': typeof AuthenticatedAppDataLakeRoute
  '/dev-kanban': typeof AuthenticatedAppDevKanbanRoute
  '/dpp': typeof AuthenticatedAppDppRoute
  '/equipe': typeof AuthenticatedAppEquipeRoute
  '/fashion-calendar': typeof AuthenticatedAppFashionCalendarRoute
  '/fashion-gpt': typeof AuthenticatedAppFashionGptRoute
  '/ficha-tecnica': typeof AuthenticatedAppFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/geo-sales': typeof AuthenticatedAppGeoSalesRoute
  '/grade-needs': typeof AuthenticatedAppGradeNeedsRoute
  '/influencer-roi': typeof AuthenticatedAppInfluencerRoiRoute
  '/influencers': typeof AuthenticatedAppInfluencersRoute
  '/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/margem': typeof AuthenticatedAppMargemRoute
  '/marketing': typeof AuthenticatedAppMarketingRoute
  '/mobile': typeof AuthenticatedAppMobileRoute
  '/movimentacoes': typeof AuthenticatedAppMovimentacoesRoute
  '/pcp': typeof AuthenticatedAppPcpRoute
  '/pcp-kanban': typeof AuthenticatedAppPcpKanbanRoute
  '/pedidos-compra': typeof AuthenticatedAppPedidosCompraRoute
  '/pilots': typeof AuthenticatedAppPilotsRoute
  '/product-score': typeof AuthenticatedAppProductScoreRoute
  '/product-success': typeof AuthenticatedAppProductSuccessRoute
  '/produtos': typeof AuthenticatedAppProdutosRoute
  '/profitability': typeof AuthenticatedAppProfitabilityRoute
  '/prototipos': typeof AuthenticatedAppPrototiposRoute
  '/replenishment': typeof AuthenticatedAppReplenishmentRoute
  '/representantes': typeof AuthenticatedAppRepresentantesRoute
  '/sales-performance': typeof AuthenticatedAppSalesPerformanceRoute
  '/security-center': typeof AuthenticatedAppSecurityCenterRoute
  '/showroom': typeof AuthenticatedAppShowroomRoute
  '/stock-health': typeof AuthenticatedAppStockHealthRoute
  '/supplier-score': typeof AuthenticatedAppSupplierScoreRoute
  '/trends': typeof AuthenticatedAppTrendsRoute
  '/twin-factory': typeof AuthenticatedAppTwinFactoryRoute
  '/use-ai': typeof AuthenticatedAppUseAiRoute
  '/api/public/agents/run-due': typeof ApiPublicAgentsRunDueRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/dpp/$id': typeof DppIdRoute
  '/almoxarifado': typeof AuthenticatedAppAlmoxarifadoRoute
  '/attribution': typeof AuthenticatedAppAttributionRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/bi': typeof AuthenticatedAppBiRoute
  '/cad': typeof AuthenticatedAppCadRoute
  '/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/capacity': typeof AuthenticatedAppCapacityRoute
  '/cashflow': typeof AuthenticatedAppCashflowRoute
  '/centro-de-corte': typeof AuthenticatedAppCentroDeCorteRoute
  '/clientes': typeof AuthenticatedAppClientesRoute
  '/colecoes': typeof AuthenticatedAppColecoesRoute
  '/comercial': typeof AuthenticatedAppComercialRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/control-tower': typeof AuthenticatedAppControlTowerRoute
  '/data-lake': typeof AuthenticatedAppDataLakeRoute
  '/dev-kanban': typeof AuthenticatedAppDevKanbanRoute
  '/dpp': typeof AuthenticatedAppDppRoute
  '/equipe': typeof AuthenticatedAppEquipeRoute
  '/fashion-calendar': typeof AuthenticatedAppFashionCalendarRoute
  '/fashion-gpt': typeof AuthenticatedAppFashionGptRoute
  '/ficha-tecnica': typeof AuthenticatedAppFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/geo-sales': typeof AuthenticatedAppGeoSalesRoute
  '/grade-needs': typeof AuthenticatedAppGradeNeedsRoute
  '/influencer-roi': typeof AuthenticatedAppInfluencerRoiRoute
  '/influencers': typeof AuthenticatedAppInfluencersRoute
  '/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/margem': typeof AuthenticatedAppMargemRoute
  '/marketing': typeof AuthenticatedAppMarketingRoute
  '/mobile': typeof AuthenticatedAppMobileRoute
  '/movimentacoes': typeof AuthenticatedAppMovimentacoesRoute
  '/pcp': typeof AuthenticatedAppPcpRoute
  '/pcp-kanban': typeof AuthenticatedAppPcpKanbanRoute
  '/pedidos-compra': typeof AuthenticatedAppPedidosCompraRoute
  '/pilots': typeof AuthenticatedAppPilotsRoute
  '/product-score': typeof AuthenticatedAppProductScoreRoute
  '/product-success': typeof AuthenticatedAppProductSuccessRoute
  '/produtos': typeof AuthenticatedAppProdutosRoute
  '/profitability': typeof AuthenticatedAppProfitabilityRoute
  '/prototipos': typeof AuthenticatedAppPrototiposRoute
  '/replenishment': typeof AuthenticatedAppReplenishmentRoute
  '/representantes': typeof AuthenticatedAppRepresentantesRoute
  '/sales-performance': typeof AuthenticatedAppSalesPerformanceRoute
  '/security-center': typeof AuthenticatedAppSecurityCenterRoute
  '/showroom': typeof AuthenticatedAppShowroomRoute
  '/stock-health': typeof AuthenticatedAppStockHealthRoute
  '/supplier-score': typeof AuthenticatedAppSupplierScoreRoute
  '/trends': typeof AuthenticatedAppTrendsRoute
  '/twin-factory': typeof AuthenticatedAppTwinFactoryRoute
  '/use-ai': typeof AuthenticatedAppUseAiRoute
  '/api/public/agents/run-due': typeof ApiPublicAgentsRunDueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/dpp/$id': typeof DppIdRoute
  '/_authenticated/_app/almoxarifado': typeof AuthenticatedAppAlmoxarifadoRoute
  '/_authenticated/_app/attribution': typeof AuthenticatedAppAttributionRoute
  '/_authenticated/_app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/_app/bi': typeof AuthenticatedAppBiRoute
  '/_authenticated/_app/cad': typeof AuthenticatedAppCadRoute
  '/_authenticated/_app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/_app/capacity': typeof AuthenticatedAppCapacityRoute
  '/_authenticated/_app/cashflow': typeof AuthenticatedAppCashflowRoute
  '/_authenticated/_app/centro-de-corte': typeof AuthenticatedAppCentroDeCorteRoute
  '/_authenticated/_app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/_app/colecoes': typeof AuthenticatedAppColecoesRoute
  '/_authenticated/_app/comercial': typeof AuthenticatedAppComercialRoute
  '/_authenticated/_app/compras': typeof AuthenticatedAppComprasRoute
  '/_authenticated/_app/control-tower': typeof AuthenticatedAppControlTowerRoute
  '/_authenticated/_app/data-lake': typeof AuthenticatedAppDataLakeRoute
  '/_authenticated/_app/dev-kanban': typeof AuthenticatedAppDevKanbanRoute
  '/_authenticated/_app/dpp': typeof AuthenticatedAppDppRoute
  '/_authenticated/_app/equipe': typeof AuthenticatedAppEquipeRoute
  '/_authenticated/_app/fashion-calendar': typeof AuthenticatedAppFashionCalendarRoute
  '/_authenticated/_app/fashion-gpt': typeof AuthenticatedAppFashionGptRoute
  '/_authenticated/_app/ficha-tecnica': typeof AuthenticatedAppFichaTecnicaRoute
  '/_authenticated/_app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/_app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/_authenticated/_app/geo-sales': typeof AuthenticatedAppGeoSalesRoute
  '/_authenticated/_app/grade-needs': typeof AuthenticatedAppGradeNeedsRoute
  '/_authenticated/_app/influencer-roi': typeof AuthenticatedAppInfluencerRoiRoute
  '/_authenticated/_app/influencers': typeof AuthenticatedAppInfluencersRoute
  '/_authenticated/_app/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/_authenticated/_app/margem': typeof AuthenticatedAppMargemRoute
  '/_authenticated/_app/marketing': typeof AuthenticatedAppMarketingRoute
  '/_authenticated/_app/mobile': typeof AuthenticatedAppMobileRoute
  '/_authenticated/_app/movimentacoes': typeof AuthenticatedAppMovimentacoesRoute
  '/_authenticated/_app/pcp': typeof AuthenticatedAppPcpRoute
  '/_authenticated/_app/pcp-kanban': typeof AuthenticatedAppPcpKanbanRoute
  '/_authenticated/_app/pedidos-compra': typeof AuthenticatedAppPedidosCompraRoute
  '/_authenticated/_app/pilots': typeof AuthenticatedAppPilotsRoute
  '/_authenticated/_app/product-score': typeof AuthenticatedAppProductScoreRoute
  '/_authenticated/_app/product-success': typeof AuthenticatedAppProductSuccessRoute
  '/_authenticated/_app/produtos': typeof AuthenticatedAppProdutosRoute
  '/_authenticated/_app/profitability': typeof AuthenticatedAppProfitabilityRoute
  '/_authenticated/_app/prototipos': typeof AuthenticatedAppPrototiposRoute
  '/_authenticated/_app/replenishment': typeof AuthenticatedAppReplenishmentRoute
  '/_authenticated/_app/representantes': typeof AuthenticatedAppRepresentantesRoute
  '/_authenticated/_app/sales-performance': typeof AuthenticatedAppSalesPerformanceRoute
  '/_authenticated/_app/security-center': typeof AuthenticatedAppSecurityCenterRoute
  '/_authenticated/_app/showroom': typeof AuthenticatedAppShowroomRoute
  '/_authenticated/_app/stock-health': typeof AuthenticatedAppStockHealthRoute
  '/_authenticated/_app/supplier-score': typeof AuthenticatedAppSupplierScoreRoute
  '/_authenticated/_app/trends': typeof AuthenticatedAppTrendsRoute
  '/_authenticated/_app/twin-factory': typeof AuthenticatedAppTwinFactoryRoute
  '/_authenticated/_app/use-ai': typeof AuthenticatedAppUseAiRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/api/public/agents/run-due': typeof ApiPublicAgentsRunDueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/dpp/$id'
    | '/almoxarifado'
    | '/attribution'
    | '/audit'
    | '/bi'
    | '/cad'
    | '/campaigns'
    | '/capacity'
    | '/cashflow'
    | '/centro-de-corte'
    | '/clientes'
    | '/colecoes'
    | '/comercial'
    | '/compras'
    | '/control-tower'
    | '/data-lake'
    | '/dev-kanban'
    | '/dpp'
    | '/equipe'
    | '/fashion-calendar'
    | '/fashion-gpt'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/fornecedores'
    | '/geo-sales'
    | '/grade-needs'
    | '/influencer-roi'
    | '/influencers'
    | '/intelligence'
    | '/margem'
    | '/marketing'
    | '/mobile'
    | '/movimentacoes'
    | '/pcp'
    | '/pcp-kanban'
    | '/pedidos-compra'
    | '/pilots'
    | '/product-score'
    | '/product-success'
    | '/produtos'
    | '/profitability'
    | '/prototipos'
    | '/replenishment'
    | '/representantes'
    | '/sales-performance'
    | '/security-center'
    | '/showroom'
    | '/stock-health'
    | '/supplier-score'
    | '/trends'
    | '/twin-factory'
    | '/use-ai'
    | '/api/public/agents/run-due'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/dpp/$id'
    | '/almoxarifado'
    | '/attribution'
    | '/audit'
    | '/bi'
    | '/cad'
    | '/campaigns'
    | '/capacity'
    | '/cashflow'
    | '/centro-de-corte'
    | '/clientes'
    | '/colecoes'
    | '/comercial'
    | '/compras'
    | '/control-tower'
    | '/data-lake'
    | '/dev-kanban'
    | '/dpp'
    | '/equipe'
    | '/fashion-calendar'
    | '/fashion-gpt'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/fornecedores'
    | '/geo-sales'
    | '/grade-needs'
    | '/influencer-roi'
    | '/influencers'
    | '/intelligence'
    | '/margem'
    | '/marketing'
    | '/mobile'
    | '/movimentacoes'
    | '/pcp'
    | '/pcp-kanban'
    | '/pedidos-compra'
    | '/pilots'
    | '/product-score'
    | '/product-success'
    | '/produtos'
    | '/profitability'
    | '/prototipos'
    | '/replenishment'
    | '/representantes'
    | '/sales-performance'
    | '/security-center'
    | '/showroom'
    | '/stock-health'
    | '/supplier-score'
    | '/trends'
    | '/twin-factory'
    | '/use-ai'
    | '/api/public/agents/run-due'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/api/chat'
    | '/dpp/$id'
    | '/_authenticated/_app/almoxarifado'
    | '/_authenticated/_app/attribution'
    | '/_authenticated/_app/audit'
    | '/_authenticated/_app/bi'
    | '/_authenticated/_app/cad'
    | '/_authenticated/_app/campaigns'
    | '/_authenticated/_app/capacity'
    | '/_authenticated/_app/cashflow'
    | '/_authenticated/_app/centro-de-corte'
    | '/_authenticated/_app/clientes'
    | '/_authenticated/_app/colecoes'
    | '/_authenticated/_app/comercial'
    | '/_authenticated/_app/compras'
    | '/_authenticated/_app/control-tower'
    | '/_authenticated/_app/data-lake'
    | '/_authenticated/_app/dev-kanban'
    | '/_authenticated/_app/dpp'
    | '/_authenticated/_app/equipe'
    | '/_authenticated/_app/fashion-calendar'
    | '/_authenticated/_app/fashion-gpt'
    | '/_authenticated/_app/ficha-tecnica'
    | '/_authenticated/_app/financeiro'
    | '/_authenticated/_app/fornecedores'
    | '/_authenticated/_app/geo-sales'
    | '/_authenticated/_app/grade-needs'
    | '/_authenticated/_app/influencer-roi'
    | '/_authenticated/_app/influencers'
    | '/_authenticated/_app/intelligence'
    | '/_authenticated/_app/margem'
    | '/_authenticated/_app/marketing'
    | '/_authenticated/_app/mobile'
    | '/_authenticated/_app/movimentacoes'
    | '/_authenticated/_app/pcp'
    | '/_authenticated/_app/pcp-kanban'
    | '/_authenticated/_app/pedidos-compra'
    | '/_authenticated/_app/pilots'
    | '/_authenticated/_app/product-score'
    | '/_authenticated/_app/product-success'
    | '/_authenticated/_app/produtos'
    | '/_authenticated/_app/profitability'
    | '/_authenticated/_app/prototipos'
    | '/_authenticated/_app/replenishment'
    | '/_authenticated/_app/representantes'
    | '/_authenticated/_app/sales-performance'
    | '/_authenticated/_app/security-center'
    | '/_authenticated/_app/showroom'
    | '/_authenticated/_app/stock-health'
    | '/_authenticated/_app/supplier-score'
    | '/_authenticated/_app/trends'
    | '/_authenticated/_app/twin-factory'
    | '/_authenticated/_app/use-ai'
    | '/_authenticated/_app/'
    | '/api/public/agents/run-due'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  DppIdRoute: typeof DppIdRoute
  ApiPublicAgentsRunDueRoute: typeof ApiPublicAgentsRunDueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp/$id': {
      id: '/dpp/$id'
      path: '/dpp/$id'
      fullPath: '/dpp/$id'
      preLoaderRoute: typeof DppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/use-ai': {
      id: '/_authenticated/_app/use-ai'
      path: '/use-ai'
      fullPath: '/use-ai'
      preLoaderRoute: typeof AuthenticatedAppUseAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/twin-factory': {
      id: '/_authenticated/_app/twin-factory'
      path: '/twin-factory'
      fullPath: '/twin-factory'
      preLoaderRoute: typeof AuthenticatedAppTwinFactoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trends': {
      id: '/_authenticated/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedAppTrendsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/supplier-score': {
      id: '/_authenticated/_app/supplier-score'
      path: '/supplier-score'
      fullPath: '/supplier-score'
      preLoaderRoute: typeof AuthenticatedAppSupplierScoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/stock-health': {
      id: '/_authenticated/_app/stock-health'
      path: '/stock-health'
      fullPath: '/stock-health'
      preLoaderRoute: typeof AuthenticatedAppStockHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/showroom': {
      id: '/_authenticated/_app/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof AuthenticatedAppShowroomRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/security-center': {
      id: '/_authenticated/_app/security-center'
      path: '/security-center'
      fullPath: '/security-center'
      preLoaderRoute: typeof AuthenticatedAppSecurityCenterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sales-performance': {
      id: '/_authenticated/_app/sales-performance'
      path: '/sales-performance'
      fullPath: '/sales-performance'
      preLoaderRoute: typeof AuthenticatedAppSalesPerformanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/representantes': {
      id: '/_authenticated/_app/representantes'
      path: '/representantes'
      fullPath: '/representantes'
      preLoaderRoute: typeof AuthenticatedAppRepresentantesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/replenishment': {
      id: '/_authenticated/_app/replenishment'
      path: '/replenishment'
      fullPath: '/replenishment'
      preLoaderRoute: typeof AuthenticatedAppReplenishmentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/prototipos': {
      id: '/_authenticated/_app/prototipos'
      path: '/prototipos'
      fullPath: '/prototipos'
      preLoaderRoute: typeof AuthenticatedAppPrototiposRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profitability': {
      id: '/_authenticated/_app/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof AuthenticatedAppProfitabilityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/produtos': {
      id: '/_authenticated/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedAppProdutosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/product-success': {
      id: '/_authenticated/_app/product-success'
      path: '/product-success'
      fullPath: '/product-success'
      preLoaderRoute: typeof AuthenticatedAppProductSuccessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/product-score': {
      id: '/_authenticated/_app/product-score'
      path: '/product-score'
      fullPath: '/product-score'
      preLoaderRoute: typeof AuthenticatedAppProductScoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pilots': {
      id: '/_authenticated/_app/pilots'
      path: '/pilots'
      fullPath: '/pilots'
      preLoaderRoute: typeof AuthenticatedAppPilotsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pedidos-compra': {
      id: '/_authenticated/_app/pedidos-compra'
      path: '/pedidos-compra'
      fullPath: '/pedidos-compra'
      preLoaderRoute: typeof AuthenticatedAppPedidosCompraRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pcp-kanban': {
      id: '/_authenticated/_app/pcp-kanban'
      path: '/pcp-kanban'
      fullPath: '/pcp-kanban'
      preLoaderRoute: typeof AuthenticatedAppPcpKanbanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pcp': {
      id: '/_authenticated/_app/pcp'
      path: '/pcp'
      fullPath: '/pcp'
      preLoaderRoute: typeof AuthenticatedAppPcpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/movimentacoes': {
      id: '/_authenticated/_app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedAppMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/mobile': {
      id: '/_authenticated/_app/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthenticatedAppMobileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/marketing': {
      id: '/_authenticated/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedAppMarketingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/margem': {
      id: '/_authenticated/_app/margem'
      path: '/margem'
      fullPath: '/margem'
      preLoaderRoute: typeof AuthenticatedAppMargemRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/intelligence': {
      id: '/_authenticated/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedAppIntelligenceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/influencers': {
      id: '/_authenticated/_app/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof AuthenticatedAppInfluencersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/influencer-roi': {
      id: '/_authenticated/_app/influencer-roi'
      path: '/influencer-roi'
      fullPath: '/influencer-roi'
      preLoaderRoute: typeof AuthenticatedAppInfluencerRoiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/grade-needs': {
      id: '/_authenticated/_app/grade-needs'
      path: '/grade-needs'
      fullPath: '/grade-needs'
      preLoaderRoute: typeof AuthenticatedAppGradeNeedsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/geo-sales': {
      id: '/_authenticated/_app/geo-sales'
      path: '/geo-sales'
      fullPath: '/geo-sales'
      preLoaderRoute: typeof AuthenticatedAppGeoSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fornecedores': {
      id: '/_authenticated/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedAppFornecedoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/financeiro': {
      id: '/_authenticated/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/ficha-tecnica': {
      id: '/_authenticated/_app/ficha-tecnica'
      path: '/ficha-tecnica'
      fullPath: '/ficha-tecnica'
      preLoaderRoute: typeof AuthenticatedAppFichaTecnicaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fashion-gpt': {
      id: '/_authenticated/_app/fashion-gpt'
      path: '/fashion-gpt'
      fullPath: '/fashion-gpt'
      preLoaderRoute: typeof AuthenticatedAppFashionGptRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fashion-calendar': {
      id: '/_authenticated/_app/fashion-calendar'
      path: '/fashion-calendar'
      fullPath: '/fashion-calendar'
      preLoaderRoute: typeof AuthenticatedAppFashionCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/equipe': {
      id: '/_authenticated/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedAppEquipeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dpp': {
      id: '/_authenticated/_app/dpp'
      path: '/dpp'
      fullPath: '/dpp'
      preLoaderRoute: typeof AuthenticatedAppDppRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dev-kanban': {
      id: '/_authenticated/_app/dev-kanban'
      path: '/dev-kanban'
      fullPath: '/dev-kanban'
      preLoaderRoute: typeof AuthenticatedAppDevKanbanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/data-lake': {
      id: '/_authenticated/_app/data-lake'
      path: '/data-lake'
      fullPath: '/data-lake'
      preLoaderRoute: typeof AuthenticatedAppDataLakeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/control-tower': {
      id: '/_authenticated/_app/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof AuthenticatedAppControlTowerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/compras': {
      id: '/_authenticated/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedAppComprasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/comercial': {
      id: '/_authenticated/_app/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedAppComercialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/colecoes': {
      id: '/_authenticated/_app/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof AuthenticatedAppColecoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/clientes': {
      id: '/_authenticated/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/centro-de-corte': {
      id: '/_authenticated/_app/centro-de-corte'
      path: '/centro-de-corte'
      fullPath: '/centro-de-corte'
      preLoaderRoute: typeof AuthenticatedAppCentroDeCorteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cashflow': {
      id: '/_authenticated/_app/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AuthenticatedAppCashflowRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/capacity': {
      id: '/_authenticated/_app/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof AuthenticatedAppCapacityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/campaigns': {
      id: '/_authenticated/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cad': {
      id: '/_authenticated/_app/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AuthenticatedAppCadRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/bi': {
      id: '/_authenticated/_app/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedAppBiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/audit': {
      id: '/_authenticated/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/attribution': {
      id: '/_authenticated/_app/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof AuthenticatedAppAttributionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/almoxarifado': {
      id: '/_authenticated/_app/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AuthenticatedAppAlmoxarifadoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/agents/run-due': {
      id: '/api/public/agents/run-due'
      path: '/api/public/agents/run-due'
      fullPath: '/api/public/agents/run-due'
      preLoaderRoute: typeof ApiPublicAgentsRunDueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlmoxarifadoRoute: typeof AuthenticatedAppAlmoxarifadoRoute
  AuthenticatedAppAttributionRoute: typeof AuthenticatedAppAttributionRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppBiRoute: typeof AuthenticatedAppBiRoute
  AuthenticatedAppCadRoute: typeof AuthenticatedAppCadRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppCapacityRoute: typeof AuthenticatedAppCapacityRoute
  AuthenticatedAppCashflowRoute: typeof AuthenticatedAppCashflowRoute
  AuthenticatedAppCentroDeCorteRoute: typeof AuthenticatedAppCentroDeCorteRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppColecoesRoute: typeof AuthenticatedAppColecoesRoute
  AuthenticatedAppComercialRoute: typeof AuthenticatedAppComercialRoute
  AuthenticatedAppComprasRoute: typeof AuthenticatedAppComprasRoute
  AuthenticatedAppControlTowerRoute: typeof AuthenticatedAppControlTowerRoute
  AuthenticatedAppDataLakeRoute: typeof AuthenticatedAppDataLakeRoute
  AuthenticatedAppDevKanbanRoute: typeof AuthenticatedAppDevKanbanRoute
  AuthenticatedAppDppRoute: typeof AuthenticatedAppDppRoute
  AuthenticatedAppEquipeRoute: typeof AuthenticatedAppEquipeRoute
  AuthenticatedAppFashionCalendarRoute: typeof AuthenticatedAppFashionCalendarRoute
  AuthenticatedAppFashionGptRoute: typeof AuthenticatedAppFashionGptRoute
  AuthenticatedAppFichaTecnicaRoute: typeof AuthenticatedAppFichaTecnicaRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppFornecedoresRoute: typeof AuthenticatedAppFornecedoresRoute
  AuthenticatedAppGeoSalesRoute: typeof AuthenticatedAppGeoSalesRoute
  AuthenticatedAppGradeNeedsRoute: typeof AuthenticatedAppGradeNeedsRoute
  AuthenticatedAppInfluencerRoiRoute: typeof AuthenticatedAppInfluencerRoiRoute
  AuthenticatedAppInfluencersRoute: typeof AuthenticatedAppInfluencersRoute
  AuthenticatedAppIntelligenceRoute: typeof AuthenticatedAppIntelligenceRoute
  AuthenticatedAppMargemRoute: typeof AuthenticatedAppMargemRoute
  AuthenticatedAppMarketingRoute: typeof AuthenticatedAppMarketingRoute
  AuthenticatedAppMobileRoute: typeof AuthenticatedAppMobileRoute
  AuthenticatedAppMovimentacoesRoute: typeof AuthenticatedAppMovimentacoesRoute
  AuthenticatedAppPcpRoute: typeof AuthenticatedAppPcpRoute
  AuthenticatedAppPcpKanbanRoute: typeof AuthenticatedAppPcpKanbanRoute
  AuthenticatedAppPedidosCompraRoute: typeof AuthenticatedAppPedidosCompraRoute
  AuthenticatedAppPilotsRoute: typeof AuthenticatedAppPilotsRoute
  AuthenticatedAppProductScoreRoute: typeof AuthenticatedAppProductScoreRoute
  AuthenticatedAppProductSuccessRoute: typeof AuthenticatedAppProductSuccessRoute
  AuthenticatedAppProdutosRoute: typeof AuthenticatedAppProdutosRoute
  AuthenticatedAppProfitabilityRoute: typeof AuthenticatedAppProfitabilityRoute
  AuthenticatedAppPrototiposRoute: typeof AuthenticatedAppPrototiposRoute
  AuthenticatedAppReplenishmentRoute: typeof AuthenticatedAppReplenishmentRoute
  AuthenticatedAppRepresentantesRoute: typeof AuthenticatedAppRepresentantesRoute
  AuthenticatedAppSalesPerformanceRoute: typeof AuthenticatedAppSalesPerformanceRoute
  AuthenticatedAppSecurityCenterRoute: typeof AuthenticatedAppSecurityCenterRoute
  AuthenticatedAppShowroomRoute: typeof AuthenticatedAppShowroomRoute
  AuthenticatedAppStockHealthRoute: typeof AuthenticatedAppStockHealthRoute
  AuthenticatedAppSupplierScoreRoute: typeof AuthenticatedAppSupplierScoreRoute
  AuthenticatedAppTrendsRoute: typeof AuthenticatedAppTrendsRoute
  AuthenticatedAppTwinFactoryRoute: typeof AuthenticatedAppTwinFactoryRoute
  AuthenticatedAppUseAiRoute: typeof AuthenticatedAppUseAiRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlmoxarifadoRoute: AuthenticatedAppAlmoxarifadoRoute,
  AuthenticatedAppAttributionRoute: AuthenticatedAppAttributionRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppBiRoute: AuthenticatedAppBiRoute,
  AuthenticatedAppCadRoute: AuthenticatedAppCadRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppCapacityRoute: AuthenticatedAppCapacityRoute,
  AuthenticatedAppCashflowRoute: AuthenticatedAppCashflowRoute,
  AuthenticatedAppCentroDeCorteRoute: AuthenticatedAppCentroDeCorteRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppColecoesRoute: AuthenticatedAppColecoesRoute,
  AuthenticatedAppComercialRoute: AuthenticatedAppComercialRoute,
  AuthenticatedAppComprasRoute: AuthenticatedAppComprasRoute,
  AuthenticatedAppControlTowerRoute: AuthenticatedAppControlTowerRoute,
  AuthenticatedAppDataLakeRoute: AuthenticatedAppDataLakeRoute,
  AuthenticatedAppDevKanbanRoute: AuthenticatedAppDevKanbanRoute,
  AuthenticatedAppDppRoute: AuthenticatedAppDppRoute,
  AuthenticatedAppEquipeRoute: AuthenticatedAppEquipeRoute,
  AuthenticatedAppFashionCalendarRoute: AuthenticatedAppFashionCalendarRoute,
  AuthenticatedAppFashionGptRoute: AuthenticatedAppFashionGptRoute,
  AuthenticatedAppFichaTecnicaRoute: AuthenticatedAppFichaTecnicaRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppFornecedoresRoute: AuthenticatedAppFornecedoresRoute,
  AuthenticatedAppGeoSalesRoute: AuthenticatedAppGeoSalesRoute,
  AuthenticatedAppGradeNeedsRoute: AuthenticatedAppGradeNeedsRoute,
  AuthenticatedAppInfluencerRoiRoute: AuthenticatedAppInfluencerRoiRoute,
  AuthenticatedAppInfluencersRoute: AuthenticatedAppInfluencersRoute,
  AuthenticatedAppIntelligenceRoute: AuthenticatedAppIntelligenceRoute,
  AuthenticatedAppMargemRoute: AuthenticatedAppMargemRoute,
  AuthenticatedAppMarketingRoute: AuthenticatedAppMarketingRoute,
  AuthenticatedAppMobileRoute: AuthenticatedAppMobileRoute,
  AuthenticatedAppMovimentacoesRoute: AuthenticatedAppMovimentacoesRoute,
  AuthenticatedAppPcpRoute: AuthenticatedAppPcpRoute,
  AuthenticatedAppPcpKanbanRoute: AuthenticatedAppPcpKanbanRoute,
  AuthenticatedAppPedidosCompraRoute: AuthenticatedAppPedidosCompraRoute,
  AuthenticatedAppPilotsRoute: AuthenticatedAppPilotsRoute,
  AuthenticatedAppProductScoreRoute: AuthenticatedAppProductScoreRoute,
  AuthenticatedAppProductSuccessRoute: AuthenticatedAppProductSuccessRoute,
  AuthenticatedAppProdutosRoute: AuthenticatedAppProdutosRoute,
  AuthenticatedAppProfitabilityRoute: AuthenticatedAppProfitabilityRoute,
  AuthenticatedAppPrototiposRoute: AuthenticatedAppPrototiposRoute,
  AuthenticatedAppReplenishmentRoute: AuthenticatedAppReplenishmentRoute,
  AuthenticatedAppRepresentantesRoute: AuthenticatedAppRepresentantesRoute,
  AuthenticatedAppSalesPerformanceRoute: AuthenticatedAppSalesPerformanceRoute,
  AuthenticatedAppSecurityCenterRoute: AuthenticatedAppSecurityCenterRoute,
  AuthenticatedAppShowroomRoute: AuthenticatedAppShowroomRoute,
  AuthenticatedAppStockHealthRoute: AuthenticatedAppStockHealthRoute,
  AuthenticatedAppSupplierScoreRoute: AuthenticatedAppSupplierScoreRoute,
  AuthenticatedAppTrendsRoute: AuthenticatedAppTrendsRoute,
  AuthenticatedAppTwinFactoryRoute: AuthenticatedAppTwinFactoryRoute,
  AuthenticatedAppUseAiRoute: AuthenticatedAppUseAiRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  DppIdRoute: DppIdRoute,
  ApiPublicAgentsRunDueRoute: ApiPublicAgentsRunDueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
