/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DppIdRouteImport } from './routes/dpp.$id'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app.index'
import { Route as PortalFornecedorTokenRouteImport } from './routes/portal.fornecedor.$token'
import { Route as AuthenticatedAppWarRoomProducaoRouteImport } from './routes/_authenticated/_app.war-room-producao'
import { Route as AuthenticatedAppVariantesRouteImport } from './routes/_authenticated/_app.variantes'
import { Route as AuthenticatedAppUseAiRouteImport } from './routes/_authenticated/_app.use-ai'
import { Route as AuthenticatedAppTwinFactoryRouteImport } from './routes/_authenticated/_app.twin-factory'
import { Route as AuthenticatedAppTrendsRouteImport } from './routes/_authenticated/_app.trends'
import { Route as AuthenticatedAppTerceirizadosRouteImport } from './routes/_authenticated/_app.terceirizados'
import { Route as AuthenticatedAppTargetCostingRouteImport } from './routes/_authenticated/_app.target-costing'
import { Route as AuthenticatedAppSustentabilidade360RouteImport } from './routes/_authenticated/_app.sustentabilidade-360'
import { Route as AuthenticatedAppSustentabilidadeRouteImport } from './routes/_authenticated/_app.sustentabilidade'
import { Route as AuthenticatedAppSupplierScoreRouteImport } from './routes/_authenticated/_app.supplier-score'
import { Route as AuthenticatedAppStockHealthRouteImport } from './routes/_authenticated/_app.stock-health'
import { Route as AuthenticatedAppSourcingRouteImport } from './routes/_authenticated/_app.sourcing'
import { Route as AuthenticatedAppShowroomRouteImport } from './routes/_authenticated/_app.showroom'
import { Route as AuthenticatedAppSecurityCenterRouteImport } from './routes/_authenticated/_app.security-center'
import { Route as AuthenticatedAppSalesPerformanceRouteImport } from './routes/_authenticated/_app.sales-performance'
import { Route as AuthenticatedAppRepresentantesRouteImport } from './routes/_authenticated/_app.representantes'
import { Route as AuthenticatedAppReplenishmentRouteImport } from './routes/_authenticated/_app.replenishment'
import { Route as AuthenticatedAppQualityRouteImport } from './routes/_authenticated/_app.quality'
import { Route as AuthenticatedAppPrototiposRouteImport } from './routes/_authenticated/_app.prototipos'
import { Route as AuthenticatedAppProfitabilityRouteImport } from './routes/_authenticated/_app.profitability'
import { Route as AuthenticatedAppProdutosRouteImport } from './routes/_authenticated/_app.produtos'
import { Route as AuthenticatedAppProductSuccessRouteImport } from './routes/_authenticated/_app.product-success'
import { Route as AuthenticatedAppProductScoreRouteImport } from './routes/_authenticated/_app.product-score'
import { Route as AuthenticatedAppPilotsRouteImport } from './routes/_authenticated/_app.pilots'
import { Route as AuthenticatedAppPedidosCompraRouteImport } from './routes/_authenticated/_app.pedidos-compra'
import { Route as AuthenticatedAppPcpStagesRouteImport } from './routes/_authenticated/_app.pcp-stages'
import { Route as AuthenticatedAppPcpKanbanRouteImport } from './routes/_authenticated/_app.pcp-kanban'
import { Route as AuthenticatedAppPcpRouteImport } from './routes/_authenticated/_app.pcp'
import { Route as AuthenticatedAppOndeEstaRouteImport } from './routes/_authenticated/_app.onde-esta'
import { Route as AuthenticatedAppOmnichannelRouteImport } from './routes/_authenticated/_app.omnichannel'
import { Route as AuthenticatedAppMovimentacoesRouteImport } from './routes/_authenticated/_app.movimentacoes'
import { Route as AuthenticatedAppMobileRouteImport } from './routes/_authenticated/_app.mobile'
import { Route as AuthenticatedAppMateriaisRouteImport } from './routes/_authenticated/_app.materiais'
import { Route as AuthenticatedAppMarketingEnviosRouteImport } from './routes/_authenticated/_app.marketing-envios'
import { Route as AuthenticatedAppMarketingRouteImport } from './routes/_authenticated/_app.marketing'
import { Route as AuthenticatedAppMargemRouteImport } from './routes/_authenticated/_app.margem'
import { Route as AuthenticatedAppLotesRouteImport } from './routes/_authenticated/_app.lotes'
import { Route as AuthenticatedAppIntelligenceRouteImport } from './routes/_authenticated/_app.intelligence'
import { Route as AuthenticatedAppIntelHubRouteImport } from './routes/_authenticated/_app.intel-hub'
import { Route as AuthenticatedAppInspecoesRouteImport } from './routes/_authenticated/_app.inspecoes'
import { Route as AuthenticatedAppInfluencersRouteImport } from './routes/_authenticated/_app.influencers'
import { Route as AuthenticatedAppInfluencerRoiRouteImport } from './routes/_authenticated/_app.influencer-roi'
import { Route as AuthenticatedAppGradeNeedsRouteImport } from './routes/_authenticated/_app.grade-needs'
import { Route as AuthenticatedAppGeoSalesRouteImport } from './routes/_authenticated/_app.geo-sales'
import { Route as AuthenticatedAppFpaRouteImport } from './routes/_authenticated/_app.fpa'
import { Route as AuthenticatedAppFornecedoresRouteImport } from './routes/_authenticated/_app.fornecedores'
import { Route as AuthenticatedAppFitSessionsRouteImport } from './routes/_authenticated/_app.fit-sessions'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/_app.financeiro'
import { Route as AuthenticatedAppFichaTecnicaRouteImport } from './routes/_authenticated/_app.ficha-tecnica'
import { Route as AuthenticatedAppFashionGptRouteImport } from './routes/_authenticated/_app.fashion-gpt'
import { Route as AuthenticatedAppFashionCalendarRouteImport } from './routes/_authenticated/_app.fashion-calendar'
import { Route as AuthenticatedAppErpIntegrationRouteImport } from './routes/_authenticated/_app.erp-integration'
import { Route as AuthenticatedAppEquipeRouteImport } from './routes/_authenticated/_app.equipe'
import { Route as AuthenticatedAppDppRouteImport } from './routes/_authenticated/_app.dpp'
import { Route as AuthenticatedAppDevKanbanRouteImport } from './routes/_authenticated/_app.dev-kanban'
import { Route as AuthenticatedAppDesignerWorkspaceRouteImport } from './routes/_authenticated/_app.designer-workspace'
import { Route as AuthenticatedAppDataLakeRouteImport } from './routes/_authenticated/_app.data-lake'
import { Route as AuthenticatedAppControlTowerRouteImport } from './routes/_authenticated/_app.control-tower'
import { Route as AuthenticatedAppComprasRouteImport } from './routes/_authenticated/_app.compras'
import { Route as AuthenticatedAppComercialRouteImport } from './routes/_authenticated/_app.comercial'
import { Route as AuthenticatedAppColecoesRouteImport } from './routes/_authenticated/_app.colecoes'
import { Route as AuthenticatedAppColecao360RouteImport } from './routes/_authenticated/_app.colecao-360'
import { Route as AuthenticatedAppClosedLoopRouteImport } from './routes/_authenticated/_app.closed-loop'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/_app.clientes'
import { Route as AuthenticatedAppCentroDeCorteRouteImport } from './routes/_authenticated/_app.centro-de-corte'
import { Route as AuthenticatedAppCashflowRouteImport } from './routes/_authenticated/_app.cashflow'
import { Route as AuthenticatedAppCapacityRouteImport } from './routes/_authenticated/_app.capacity'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/_app.campaigns'
import { Route as AuthenticatedAppCadeia360RouteImport } from './routes/_authenticated/_app.cadeia-360'
import { Route as AuthenticatedAppCadRouteImport } from './routes/_authenticated/_app.cad'
import { Route as AuthenticatedAppBiRouteImport } from './routes/_authenticated/_app.bi'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/_app.audit'
import { Route as AuthenticatedAppAttributionRouteImport } from './routes/_authenticated/_app.attribution'
import { Route as AuthenticatedAppApprovalsRouteImport } from './routes/_authenticated/_app.approvals'
import { Route as AuthenticatedAppAlmoxarifadoRouteImport } from './routes/_authenticated/_app.almoxarifado'
import { Route as ApiPublicSupplierPortalTokenRouteImport } from './routes/api/public/supplier-portal.$token'
import { Route as ApiPublicErpSyncPublicIdRouteImport } from './routes/api/public/erp-sync.$publicId'
import { Route as ApiPublicAgentsRunDueRouteImport } from './routes/api.public.agents.run-due'
import { Route as AuthenticatedAppWarRoomColecaoIdRouteImport } from './routes/_authenticated/_app.war-room-colecao.$id'
import { Route as AuthenticatedAppProducaoDoDiaStageRouteImport } from './routes/_authenticated/_app.producao-do-dia.$stage'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DppIdRoute = DppIdRouteImport.update({
  id: '/dpp/$id',
  path: '/dpp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const PortalFornecedorTokenRoute = PortalFornecedorTokenRouteImport.update({
  id: '/portal/fornecedor/$token',
  path: '/portal/fornecedor/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWarRoomProducaoRoute =
  AuthenticatedAppWarRoomProducaoRouteImport.update({
    id: '/war-room-producao',
    path: '/war-room-producao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVariantesRoute =
  AuthenticatedAppVariantesRouteImport.update({
    id: '/variantes',
    path: '/variantes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUseAiRoute = AuthenticatedAppUseAiRouteImport.update({
  id: '/use-ai',
  path: '/use-ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTwinFactoryRoute =
  AuthenticatedAppTwinFactoryRouteImport.update({
    id: '/twin-factory',
    path: '/twin-factory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrendsRoute = AuthenticatedAppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTerceirizadosRoute =
  AuthenticatedAppTerceirizadosRouteImport.update({
    id: '/terceirizados',
    path: '/terceirizados',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTargetCostingRoute =
  AuthenticatedAppTargetCostingRouteImport.update({
    id: '/target-costing',
    path: '/target-costing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSustentabilidade360Route =
  AuthenticatedAppSustentabilidade360RouteImport.update({
    id: '/sustentabilidade-360',
    path: '/sustentabilidade-360',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSustentabilidadeRoute =
  AuthenticatedAppSustentabilidadeRouteImport.update({
    id: '/sustentabilidade',
    path: '/sustentabilidade',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSupplierScoreRoute =
  AuthenticatedAppSupplierScoreRouteImport.update({
    id: '/supplier-score',
    path: '/supplier-score',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStockHealthRoute =
  AuthenticatedAppStockHealthRouteImport.update({
    id: '/stock-health',
    path: '/stock-health',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSourcingRoute =
  AuthenticatedAppSourcingRouteImport.update({
    id: '/sourcing',
    path: '/sourcing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppShowroomRoute =
  AuthenticatedAppShowroomRouteImport.update({
    id: '/showroom',
    path: '/showroom',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSecurityCenterRoute =
  AuthenticatedAppSecurityCenterRouteImport.update({
    id: '/security-center',
    path: '/security-center',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSalesPerformanceRoute =
  AuthenticatedAppSalesPerformanceRouteImport.update({
    id: '/sales-performance',
    path: '/sales-performance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRepresentantesRoute =
  AuthenticatedAppRepresentantesRouteImport.update({
    id: '/representantes',
    path: '/representantes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReplenishmentRoute =
  AuthenticatedAppReplenishmentRouteImport.update({
    id: '/replenishment',
    path: '/replenishment',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQualityRoute = AuthenticatedAppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPrototiposRoute =
  AuthenticatedAppPrototiposRouteImport.update({
    id: '/prototipos',
    path: '/prototipos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfitabilityRoute =
  AuthenticatedAppProfitabilityRouteImport.update({
    id: '/profitability',
    path: '/profitability',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProdutosRoute =
  AuthenticatedAppProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductSuccessRoute =
  AuthenticatedAppProductSuccessRouteImport.update({
    id: '/product-success',
    path: '/product-success',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductScoreRoute =
  AuthenticatedAppProductScoreRouteImport.update({
    id: '/product-score',
    path: '/product-score',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPilotsRoute = AuthenticatedAppPilotsRouteImport.update({
  id: '/pilots',
  path: '/pilots',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPedidosCompraRoute =
  AuthenticatedAppPedidosCompraRouteImport.update({
    id: '/pedidos-compra',
    path: '/pedidos-compra',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPcpStagesRoute =
  AuthenticatedAppPcpStagesRouteImport.update({
    id: '/pcp-stages',
    path: '/pcp-stages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPcpKanbanRoute =
  AuthenticatedAppPcpKanbanRouteImport.update({
    id: '/pcp-kanban',
    path: '/pcp-kanban',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPcpRoute = AuthenticatedAppPcpRouteImport.update({
  id: '/pcp',
  path: '/pcp',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOndeEstaRoute =
  AuthenticatedAppOndeEstaRouteImport.update({
    id: '/onde-esta',
    path: '/onde-esta',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOmnichannelRoute =
  AuthenticatedAppOmnichannelRouteImport.update({
    id: '/omnichannel',
    path: '/omnichannel',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMovimentacoesRoute =
  AuthenticatedAppMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMobileRoute = AuthenticatedAppMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMateriaisRoute =
  AuthenticatedAppMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMarketingEnviosRoute =
  AuthenticatedAppMarketingEnviosRouteImport.update({
    id: '/marketing-envios',
    path: '/marketing-envios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMarketingRoute =
  AuthenticatedAppMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMargemRoute = AuthenticatedAppMargemRouteImport.update({
  id: '/margem',
  path: '/margem',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLotesRoute = AuthenticatedAppLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntelligenceRoute =
  AuthenticatedAppIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIntelHubRoute =
  AuthenticatedAppIntelHubRouteImport.update({
    id: '/intel-hub',
    path: '/intel-hub',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInspecoesRoute =
  AuthenticatedAppInspecoesRouteImport.update({
    id: '/inspecoes',
    path: '/inspecoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInfluencersRoute =
  AuthenticatedAppInfluencersRouteImport.update({
    id: '/influencers',
    path: '/influencers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInfluencerRoiRoute =
  AuthenticatedAppInfluencerRoiRouteImport.update({
    id: '/influencer-roi',
    path: '/influencer-roi',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGradeNeedsRoute =
  AuthenticatedAppGradeNeedsRouteImport.update({
    id: '/grade-needs',
    path: '/grade-needs',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGeoSalesRoute =
  AuthenticatedAppGeoSalesRouteImport.update({
    id: '/geo-sales',
    path: '/geo-sales',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFpaRoute = AuthenticatedAppFpaRouteImport.update({
  id: '/fpa',
  path: '/fpa',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFornecedoresRoute =
  AuthenticatedAppFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFitSessionsRoute =
  AuthenticatedAppFitSessionsRouteImport.update({
    id: '/fit-sessions',
    path: '/fit-sessions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFichaTecnicaRoute =
  AuthenticatedAppFichaTecnicaRouteImport.update({
    id: '/ficha-tecnica',
    path: '/ficha-tecnica',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFashionGptRoute =
  AuthenticatedAppFashionGptRouteImport.update({
    id: '/fashion-gpt',
    path: '/fashion-gpt',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFashionCalendarRoute =
  AuthenticatedAppFashionCalendarRouteImport.update({
    id: '/fashion-calendar',
    path: '/fashion-calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppErpIntegrationRoute =
  AuthenticatedAppErpIntegrationRouteImport.update({
    id: '/erp-integration',
    path: '/erp-integration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEquipeRoute = AuthenticatedAppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDppRoute = AuthenticatedAppDppRouteImport.update({
  id: '/dpp',
  path: '/dpp',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDevKanbanRoute =
  AuthenticatedAppDevKanbanRouteImport.update({
    id: '/dev-kanban',
    path: '/dev-kanban',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDesignerWorkspaceRoute =
  AuthenticatedAppDesignerWorkspaceRouteImport.update({
    id: '/designer-workspace',
    path: '/designer-workspace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDataLakeRoute =
  AuthenticatedAppDataLakeRouteImport.update({
    id: '/data-lake',
    path: '/data-lake',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppControlTowerRoute =
  AuthenticatedAppControlTowerRouteImport.update({
    id: '/control-tower',
    path: '/control-tower',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComprasRoute = AuthenticatedAppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComercialRoute =
  AuthenticatedAppComercialRouteImport.update({
    id: '/comercial',
    path: '/comercial',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppColecoesRoute =
  AuthenticatedAppColecoesRouteImport.update({
    id: '/colecoes',
    path: '/colecoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppColecao360Route =
  AuthenticatedAppColecao360RouteImport.update({
    id: '/colecao-360',
    path: '/colecao-360',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClosedLoopRoute =
  AuthenticatedAppClosedLoopRouteImport.update({
    id: '/closed-loop',
    path: '/closed-loop',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCentroDeCorteRoute =
  AuthenticatedAppCentroDeCorteRouteImport.update({
    id: '/centro-de-corte',
    path: '/centro-de-corte',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCashflowRoute =
  AuthenticatedAppCashflowRouteImport.update({
    id: '/cashflow',
    path: '/cashflow',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCapacityRoute =
  AuthenticatedAppCapacityRouteImport.update({
    id: '/capacity',
    path: '/capacity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCadeia360Route =
  AuthenticatedAppCadeia360RouteImport.update({
    id: '/cadeia-360',
    path: '/cadeia-360',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCadRoute = AuthenticatedAppCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBiRoute = AuthenticatedAppBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAttributionRoute =
  AuthenticatedAppAttributionRouteImport.update({
    id: '/attribution',
    path: '/attribution',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppApprovalsRoute =
  AuthenticatedAppApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlmoxarifadoRoute =
  AuthenticatedAppAlmoxarifadoRouteImport.update({
    id: '/almoxarifado',
    path: '/almoxarifado',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicSupplierPortalTokenRoute =
  ApiPublicSupplierPortalTokenRouteImport.update({
    id: '/api/public/supplier-portal/$token',
    path: '/api/public/supplier-portal/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicErpSyncPublicIdRoute =
  ApiPublicErpSyncPublicIdRouteImport.update({
    id: '/api/public/erp-sync/$publicId',
    path: '/api/public/erp-sync/$publicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsRunDueRoute = ApiPublicAgentsRunDueRouteImport.update({
  id: '/api/public/agents/run-due',
  path: '/api/public/agents/run-due',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWarRoomColecaoIdRoute =
  AuthenticatedAppWarRoomColecaoIdRouteImport.update({
    id: '/war-room-colecao/$id',
    path: '/war-room-colecao/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProducaoDoDiaStageRoute =
  AuthenticatedAppProducaoDoDiaStageRouteImport.update({
    id: '/producao-do-dia/$stage',
    path: '/producao-do-dia/$stage',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/dpp/$id': typeof DppIdRoute
  '/almoxarifado': typeof AuthenticatedAppAlmoxarifadoRoute
  '/approvals': typeof AuthenticatedAppApprovalsRoute
  '/attribution': typeof AuthenticatedAppAttributionRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/bi': typeof AuthenticatedAppBiRoute
  '/cad': typeof AuthenticatedAppCadRoute
  '/cadeia-360': typeof AuthenticatedAppCadeia360Route
  '/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/capacity': typeof AuthenticatedAppCapacityRoute
  '/cashflow': typeof AuthenticatedAppCashflowRoute
  '/centro-de-corte': typeof AuthenticatedAppCentroDeCorteRoute
  '/clientes': typeof AuthenticatedAppClientesRoute
  '/closed-loop': typeof AuthenticatedAppClosedLoopRoute
  '/colecao-360': typeof AuthenticatedAppColecao360Route
  '/colecoes': typeof AuthenticatedAppColecoesRoute
  '/comercial': typeof AuthenticatedAppComercialRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/control-tower': typeof AuthenticatedAppControlTowerRoute
  '/data-lake': typeof AuthenticatedAppDataLakeRoute
  '/designer-workspace': typeof AuthenticatedAppDesignerWorkspaceRoute
  '/dev-kanban': typeof AuthenticatedAppDevKanbanRoute
  '/dpp': typeof AuthenticatedAppDppRoute
  '/equipe': typeof AuthenticatedAppEquipeRoute
  '/erp-integration': typeof AuthenticatedAppErpIntegrationRoute
  '/fashion-calendar': typeof AuthenticatedAppFashionCalendarRoute
  '/fashion-gpt': typeof AuthenticatedAppFashionGptRoute
  '/ficha-tecnica': typeof AuthenticatedAppFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/fit-sessions': typeof AuthenticatedAppFitSessionsRoute
  '/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/fpa': typeof AuthenticatedAppFpaRoute
  '/geo-sales': typeof AuthenticatedAppGeoSalesRoute
  '/grade-needs': typeof AuthenticatedAppGradeNeedsRoute
  '/influencer-roi': typeof AuthenticatedAppInfluencerRoiRoute
  '/influencers': typeof AuthenticatedAppInfluencersRoute
  '/inspecoes': typeof AuthenticatedAppInspecoesRoute
  '/intel-hub': typeof AuthenticatedAppIntelHubRoute
  '/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/lotes': typeof AuthenticatedAppLotesRoute
  '/margem': typeof AuthenticatedAppMargemRoute
  '/marketing': typeof AuthenticatedAppMarketingRoute
  '/marketing-envios': typeof AuthenticatedAppMarketingEnviosRoute
  '/materiais': typeof AuthenticatedAppMateriaisRoute
  '/mobile': typeof AuthenticatedAppMobileRoute
  '/movimentacoes': typeof AuthenticatedAppMovimentacoesRoute
  '/omnichannel': typeof AuthenticatedAppOmnichannelRoute
  '/onde-esta': typeof AuthenticatedAppOndeEstaRoute
  '/pcp': typeof AuthenticatedAppPcpRoute
  '/pcp-kanban': typeof AuthenticatedAppPcpKanbanRoute
  '/pcp-stages': typeof AuthenticatedAppPcpStagesRoute
  '/pedidos-compra': typeof AuthenticatedAppPedidosCompraRoute
  '/pilots': typeof AuthenticatedAppPilotsRoute
  '/product-score': typeof AuthenticatedAppProductScoreRoute
  '/product-success': typeof AuthenticatedAppProductSuccessRoute
  '/produtos': typeof AuthenticatedAppProdutosRoute
  '/profitability': typeof AuthenticatedAppProfitabilityRoute
  '/prototipos': typeof AuthenticatedAppPrototiposRoute
  '/quality': typeof AuthenticatedAppQualityRoute
  '/replenishment': typeof AuthenticatedAppReplenishmentRoute
  '/representantes': typeof AuthenticatedAppRepresentantesRoute
  '/sales-performance': typeof AuthenticatedAppSalesPerformanceRoute
  '/security-center': typeof AuthenticatedAppSecurityCenterRoute
  '/showroom': typeof AuthenticatedAppShowroomRoute
  '/sourcing': typeof AuthenticatedAppSourcingRoute
  '/stock-health': typeof AuthenticatedAppStockHealthRoute
  '/supplier-score': typeof AuthenticatedAppSupplierScoreRoute
  '/sustentabilidade': typeof AuthenticatedAppSustentabilidadeRoute
  '/sustentabilidade-360': typeof AuthenticatedAppSustentabilidade360Route
  '/target-costing': typeof AuthenticatedAppTargetCostingRoute
  '/terceirizados': typeof AuthenticatedAppTerceirizadosRoute
  '/trends': typeof AuthenticatedAppTrendsRoute
  '/twin-factory': typeof AuthenticatedAppTwinFactoryRoute
  '/use-ai': typeof AuthenticatedAppUseAiRoute
  '/variantes': typeof AuthenticatedAppVariantesRoute
  '/war-room-producao': typeof AuthenticatedAppWarRoomProducaoRoute
  '/portal/fornecedor/$token': typeof PortalFornecedorTokenRoute
  '/producao-do-dia/$stage': typeof AuthenticatedAppProducaoDoDiaStageRoute
  '/war-room-colecao/$id': typeof AuthenticatedAppWarRoomColecaoIdRoute
  '/api/public/agents/run-due': typeof ApiPublicAgentsRunDueRoute
  '/api/public/erp-sync/$publicId': typeof ApiPublicErpSyncPublicIdRoute
  '/api/public/supplier-portal/$token': typeof ApiPublicSupplierPortalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/dpp/$id': typeof DppIdRoute
  '/almoxarifado': typeof AuthenticatedAppAlmoxarifadoRoute
  '/approvals': typeof AuthenticatedAppApprovalsRoute
  '/attribution': typeof AuthenticatedAppAttributionRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/bi': typeof AuthenticatedAppBiRoute
  '/cad': typeof AuthenticatedAppCadRoute
  '/cadeia-360': typeof AuthenticatedAppCadeia360Route
  '/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/capacity': typeof AuthenticatedAppCapacityRoute
  '/cashflow': typeof AuthenticatedAppCashflowRoute
  '/centro-de-corte': typeof AuthenticatedAppCentroDeCorteRoute
  '/clientes': typeof AuthenticatedAppClientesRoute
  '/closed-loop': typeof AuthenticatedAppClosedLoopRoute
  '/colecao-360': typeof AuthenticatedAppColecao360Route
  '/colecoes': typeof AuthenticatedAppColecoesRoute
  '/comercial': typeof AuthenticatedAppComercialRoute
  '/compras': typeof AuthenticatedAppComprasRoute
  '/control-tower': typeof AuthenticatedAppControlTowerRoute
  '/data-lake': typeof AuthenticatedAppDataLakeRoute
  '/designer-workspace': typeof AuthenticatedAppDesignerWorkspaceRoute
  '/dev-kanban': typeof AuthenticatedAppDevKanbanRoute
  '/dpp': typeof AuthenticatedAppDppRoute
  '/equipe': typeof AuthenticatedAppEquipeRoute
  '/erp-integration': typeof AuthenticatedAppErpIntegrationRoute
  '/fashion-calendar': typeof AuthenticatedAppFashionCalendarRoute
  '/fashion-gpt': typeof AuthenticatedAppFashionGptRoute
  '/ficha-tecnica': typeof AuthenticatedAppFichaTecnicaRoute
  '/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/fit-sessions': typeof AuthenticatedAppFitSessionsRoute
  '/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/fpa': typeof AuthenticatedAppFpaRoute
  '/geo-sales': typeof AuthenticatedAppGeoSalesRoute
  '/grade-needs': typeof AuthenticatedAppGradeNeedsRoute
  '/influencer-roi': typeof AuthenticatedAppInfluencerRoiRoute
  '/influencers': typeof AuthenticatedAppInfluencersRoute
  '/inspecoes': typeof AuthenticatedAppInspecoesRoute
  '/intel-hub': typeof AuthenticatedAppIntelHubRoute
  '/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/lotes': typeof AuthenticatedAppLotesRoute
  '/margem': typeof AuthenticatedAppMargemRoute
  '/marketing': typeof AuthenticatedAppMarketingRoute
  '/marketing-envios': typeof AuthenticatedAppMarketingEnviosRoute
  '/materiais': typeof AuthenticatedAppMateriaisRoute
  '/mobile': typeof AuthenticatedAppMobileRoute
  '/movimentacoes': typeof AuthenticatedAppMovimentacoesRoute
  '/omnichannel': typeof AuthenticatedAppOmnichannelRoute
  '/onde-esta': typeof AuthenticatedAppOndeEstaRoute
  '/pcp': typeof AuthenticatedAppPcpRoute
  '/pcp-kanban': typeof AuthenticatedAppPcpKanbanRoute
  '/pcp-stages': typeof AuthenticatedAppPcpStagesRoute
  '/pedidos-compra': typeof AuthenticatedAppPedidosCompraRoute
  '/pilots': typeof AuthenticatedAppPilotsRoute
  '/product-score': typeof AuthenticatedAppProductScoreRoute
  '/product-success': typeof AuthenticatedAppProductSuccessRoute
  '/produtos': typeof AuthenticatedAppProdutosRoute
  '/profitability': typeof AuthenticatedAppProfitabilityRoute
  '/prototipos': typeof AuthenticatedAppPrototiposRoute
  '/quality': typeof AuthenticatedAppQualityRoute
  '/replenishment': typeof AuthenticatedAppReplenishmentRoute
  '/representantes': typeof AuthenticatedAppRepresentantesRoute
  '/sales-performance': typeof AuthenticatedAppSalesPerformanceRoute
  '/security-center': typeof AuthenticatedAppSecurityCenterRoute
  '/showroom': typeof AuthenticatedAppShowroomRoute
  '/sourcing': typeof AuthenticatedAppSourcingRoute
  '/stock-health': typeof AuthenticatedAppStockHealthRoute
  '/supplier-score': typeof AuthenticatedAppSupplierScoreRoute
  '/sustentabilidade': typeof AuthenticatedAppSustentabilidadeRoute
  '/sustentabilidade-360': typeof AuthenticatedAppSustentabilidade360Route
  '/target-costing': typeof AuthenticatedAppTargetCostingRoute
  '/terceirizados': typeof AuthenticatedAppTerceirizadosRoute
  '/trends': typeof AuthenticatedAppTrendsRoute
  '/twin-factory': typeof AuthenticatedAppTwinFactoryRoute
  '/use-ai': typeof AuthenticatedAppUseAiRoute
  '/variantes': typeof AuthenticatedAppVariantesRoute
  '/war-room-producao': typeof AuthenticatedAppWarRoomProducaoRoute
  '/portal/fornecedor/$token': typeof PortalFornecedorTokenRoute
  '/producao-do-dia/$stage': typeof AuthenticatedAppProducaoDoDiaStageRoute
  '/war-room-colecao/$id': typeof AuthenticatedAppWarRoomColecaoIdRoute
  '/api/public/agents/run-due': typeof ApiPublicAgentsRunDueRoute
  '/api/public/erp-sync/$publicId': typeof ApiPublicErpSyncPublicIdRoute
  '/api/public/supplier-portal/$token': typeof ApiPublicSupplierPortalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/dpp/$id': typeof DppIdRoute
  '/_authenticated/_app/almoxarifado': typeof AuthenticatedAppAlmoxarifadoRoute
  '/_authenticated/_app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/_authenticated/_app/attribution': typeof AuthenticatedAppAttributionRoute
  '/_authenticated/_app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/_app/bi': typeof AuthenticatedAppBiRoute
  '/_authenticated/_app/cad': typeof AuthenticatedAppCadRoute
  '/_authenticated/_app/cadeia-360': typeof AuthenticatedAppCadeia360Route
  '/_authenticated/_app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/_app/capacity': typeof AuthenticatedAppCapacityRoute
  '/_authenticated/_app/cashflow': typeof AuthenticatedAppCashflowRoute
  '/_authenticated/_app/centro-de-corte': typeof AuthenticatedAppCentroDeCorteRoute
  '/_authenticated/_app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/_app/closed-loop': typeof AuthenticatedAppClosedLoopRoute
  '/_authenticated/_app/colecao-360': typeof AuthenticatedAppColecao360Route
  '/_authenticated/_app/colecoes': typeof AuthenticatedAppColecoesRoute
  '/_authenticated/_app/comercial': typeof AuthenticatedAppComercialRoute
  '/_authenticated/_app/compras': typeof AuthenticatedAppComprasRoute
  '/_authenticated/_app/control-tower': typeof AuthenticatedAppControlTowerRoute
  '/_authenticated/_app/data-lake': typeof AuthenticatedAppDataLakeRoute
  '/_authenticated/_app/designer-workspace': typeof AuthenticatedAppDesignerWorkspaceRoute
  '/_authenticated/_app/dev-kanban': typeof AuthenticatedAppDevKanbanRoute
  '/_authenticated/_app/dpp': typeof AuthenticatedAppDppRoute
  '/_authenticated/_app/equipe': typeof AuthenticatedAppEquipeRoute
  '/_authenticated/_app/erp-integration': typeof AuthenticatedAppErpIntegrationRoute
  '/_authenticated/_app/fashion-calendar': typeof AuthenticatedAppFashionCalendarRoute
  '/_authenticated/_app/fashion-gpt': typeof AuthenticatedAppFashionGptRoute
  '/_authenticated/_app/ficha-tecnica': typeof AuthenticatedAppFichaTecnicaRoute
  '/_authenticated/_app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/_app/fit-sessions': typeof AuthenticatedAppFitSessionsRoute
  '/_authenticated/_app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/_authenticated/_app/fpa': typeof AuthenticatedAppFpaRoute
  '/_authenticated/_app/geo-sales': typeof AuthenticatedAppGeoSalesRoute
  '/_authenticated/_app/grade-needs': typeof AuthenticatedAppGradeNeedsRoute
  '/_authenticated/_app/influencer-roi': typeof AuthenticatedAppInfluencerRoiRoute
  '/_authenticated/_app/influencers': typeof AuthenticatedAppInfluencersRoute
  '/_authenticated/_app/inspecoes': typeof AuthenticatedAppInspecoesRoute
  '/_authenticated/_app/intel-hub': typeof AuthenticatedAppIntelHubRoute
  '/_authenticated/_app/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/_authenticated/_app/lotes': typeof AuthenticatedAppLotesRoute
  '/_authenticated/_app/margem': typeof AuthenticatedAppMargemRoute
  '/_authenticated/_app/marketing': typeof AuthenticatedAppMarketingRoute
  '/_authenticated/_app/marketing-envios': typeof AuthenticatedAppMarketingEnviosRoute
  '/_authenticated/_app/materiais': typeof AuthenticatedAppMateriaisRoute
  '/_authenticated/_app/mobile': typeof AuthenticatedAppMobileRoute
  '/_authenticated/_app/movimentacoes': typeof AuthenticatedAppMovimentacoesRoute
  '/_authenticated/_app/omnichannel': typeof AuthenticatedAppOmnichannelRoute
  '/_authenticated/_app/onde-esta': typeof AuthenticatedAppOndeEstaRoute
  '/_authenticated/_app/pcp': typeof AuthenticatedAppPcpRoute
  '/_authenticated/_app/pcp-kanban': typeof AuthenticatedAppPcpKanbanRoute
  '/_authenticated/_app/pcp-stages': typeof AuthenticatedAppPcpStagesRoute
  '/_authenticated/_app/pedidos-compra': typeof AuthenticatedAppPedidosCompraRoute
  '/_authenticated/_app/pilots': typeof AuthenticatedAppPilotsRoute
  '/_authenticated/_app/product-score': typeof AuthenticatedAppProductScoreRoute
  '/_authenticated/_app/product-success': typeof AuthenticatedAppProductSuccessRoute
  '/_authenticated/_app/produtos': typeof AuthenticatedAppProdutosRoute
  '/_authenticated/_app/profitability': typeof AuthenticatedAppProfitabilityRoute
  '/_authenticated/_app/prototipos': typeof AuthenticatedAppPrototiposRoute
  '/_authenticated/_app/quality': typeof AuthenticatedAppQualityRoute
  '/_authenticated/_app/replenishment': typeof AuthenticatedAppReplenishmentRoute
  '/_authenticated/_app/representantes': typeof AuthenticatedAppRepresentantesRoute
  '/_authenticated/_app/sales-performance': typeof AuthenticatedAppSalesPerformanceRoute
  '/_authenticated/_app/security-center': typeof AuthenticatedAppSecurityCenterRoute
  '/_authenticated/_app/showroom': typeof AuthenticatedAppShowroomRoute
  '/_authenticated/_app/sourcing': typeof AuthenticatedAppSourcingRoute
  '/_authenticated/_app/stock-health': typeof AuthenticatedAppStockHealthRoute
  '/_authenticated/_app/supplier-score': typeof AuthenticatedAppSupplierScoreRoute
  '/_authenticated/_app/sustentabilidade': typeof AuthenticatedAppSustentabilidadeRoute
  '/_authenticated/_app/sustentabilidade-360': typeof AuthenticatedAppSustentabilidade360Route
  '/_authenticated/_app/target-costing': typeof AuthenticatedAppTargetCostingRoute
  '/_authenticated/_app/terceirizados': typeof AuthenticatedAppTerceirizadosRoute
  '/_authenticated/_app/trends': typeof AuthenticatedAppTrendsRoute
  '/_authenticated/_app/twin-factory': typeof AuthenticatedAppTwinFactoryRoute
  '/_authenticated/_app/use-ai': typeof AuthenticatedAppUseAiRoute
  '/_authenticated/_app/variantes': typeof AuthenticatedAppVariantesRoute
  '/_authenticated/_app/war-room-producao': typeof AuthenticatedAppWarRoomProducaoRoute
  '/portal/fornecedor/$token': typeof PortalFornecedorTokenRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/producao-do-dia/$stage': typeof AuthenticatedAppProducaoDoDiaStageRoute
  '/_authenticated/_app/war-room-colecao/$id': typeof AuthenticatedAppWarRoomColecaoIdRoute
  '/api/public/agents/run-due': typeof ApiPublicAgentsRunDueRoute
  '/api/public/erp-sync/$publicId': typeof ApiPublicErpSyncPublicIdRoute
  '/api/public/supplier-portal/$token': typeof ApiPublicSupplierPortalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/dpp/$id'
    | '/almoxarifado'
    | '/approvals'
    | '/attribution'
    | '/audit'
    | '/bi'
    | '/cad'
    | '/cadeia-360'
    | '/campaigns'
    | '/capacity'
    | '/cashflow'
    | '/centro-de-corte'
    | '/clientes'
    | '/closed-loop'
    | '/colecao-360'
    | '/colecoes'
    | '/comercial'
    | '/compras'
    | '/control-tower'
    | '/data-lake'
    | '/designer-workspace'
    | '/dev-kanban'
    | '/dpp'
    | '/equipe'
    | '/erp-integration'
    | '/fashion-calendar'
    | '/fashion-gpt'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/fit-sessions'
    | '/fornecedores'
    | '/fpa'
    | '/geo-sales'
    | '/grade-needs'
    | '/influencer-roi'
    | '/influencers'
    | '/inspecoes'
    | '/intel-hub'
    | '/intelligence'
    | '/lotes'
    | '/margem'
    | '/marketing'
    | '/marketing-envios'
    | '/materiais'
    | '/mobile'
    | '/movimentacoes'
    | '/omnichannel'
    | '/onde-esta'
    | '/pcp'
    | '/pcp-kanban'
    | '/pcp-stages'
    | '/pedidos-compra'
    | '/pilots'
    | '/product-score'
    | '/product-success'
    | '/produtos'
    | '/profitability'
    | '/prototipos'
    | '/quality'
    | '/replenishment'
    | '/representantes'
    | '/sales-performance'
    | '/security-center'
    | '/showroom'
    | '/sourcing'
    | '/stock-health'
    | '/supplier-score'
    | '/sustentabilidade'
    | '/sustentabilidade-360'
    | '/target-costing'
    | '/terceirizados'
    | '/trends'
    | '/twin-factory'
    | '/use-ai'
    | '/variantes'
    | '/war-room-producao'
    | '/portal/fornecedor/$token'
    | '/producao-do-dia/$stage'
    | '/war-room-colecao/$id'
    | '/api/public/agents/run-due'
    | '/api/public/erp-sync/$publicId'
    | '/api/public/supplier-portal/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/dpp/$id'
    | '/almoxarifado'
    | '/approvals'
    | '/attribution'
    | '/audit'
    | '/bi'
    | '/cad'
    | '/cadeia-360'
    | '/campaigns'
    | '/capacity'
    | '/cashflow'
    | '/centro-de-corte'
    | '/clientes'
    | '/closed-loop'
    | '/colecao-360'
    | '/colecoes'
    | '/comercial'
    | '/compras'
    | '/control-tower'
    | '/data-lake'
    | '/designer-workspace'
    | '/dev-kanban'
    | '/dpp'
    | '/equipe'
    | '/erp-integration'
    | '/fashion-calendar'
    | '/fashion-gpt'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/fit-sessions'
    | '/fornecedores'
    | '/fpa'
    | '/geo-sales'
    | '/grade-needs'
    | '/influencer-roi'
    | '/influencers'
    | '/inspecoes'
    | '/intel-hub'
    | '/intelligence'
    | '/lotes'
    | '/margem'
    | '/marketing'
    | '/marketing-envios'
    | '/materiais'
    | '/mobile'
    | '/movimentacoes'
    | '/omnichannel'
    | '/onde-esta'
    | '/pcp'
    | '/pcp-kanban'
    | '/pcp-stages'
    | '/pedidos-compra'
    | '/pilots'
    | '/product-score'
    | '/product-success'
    | '/produtos'
    | '/profitability'
    | '/prototipos'
    | '/quality'
    | '/replenishment'
    | '/representantes'
    | '/sales-performance'
    | '/security-center'
    | '/showroom'
    | '/sourcing'
    | '/stock-health'
    | '/supplier-score'
    | '/sustentabilidade'
    | '/sustentabilidade-360'
    | '/target-costing'
    | '/terceirizados'
    | '/trends'
    | '/twin-factory'
    | '/use-ai'
    | '/variantes'
    | '/war-room-producao'
    | '/portal/fornecedor/$token'
    | '/producao-do-dia/$stage'
    | '/war-room-colecao/$id'
    | '/api/public/agents/run-due'
    | '/api/public/erp-sync/$publicId'
    | '/api/public/supplier-portal/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/api/chat'
    | '/dpp/$id'
    | '/_authenticated/_app/almoxarifado'
    | '/_authenticated/_app/approvals'
    | '/_authenticated/_app/attribution'
    | '/_authenticated/_app/audit'
    | '/_authenticated/_app/bi'
    | '/_authenticated/_app/cad'
    | '/_authenticated/_app/cadeia-360'
    | '/_authenticated/_app/campaigns'
    | '/_authenticated/_app/capacity'
    | '/_authenticated/_app/cashflow'
    | '/_authenticated/_app/centro-de-corte'
    | '/_authenticated/_app/clientes'
    | '/_authenticated/_app/closed-loop'
    | '/_authenticated/_app/colecao-360'
    | '/_authenticated/_app/colecoes'
    | '/_authenticated/_app/comercial'
    | '/_authenticated/_app/compras'
    | '/_authenticated/_app/control-tower'
    | '/_authenticated/_app/data-lake'
    | '/_authenticated/_app/designer-workspace'
    | '/_authenticated/_app/dev-kanban'
    | '/_authenticated/_app/dpp'
    | '/_authenticated/_app/equipe'
    | '/_authenticated/_app/erp-integration'
    | '/_authenticated/_app/fashion-calendar'
    | '/_authenticated/_app/fashion-gpt'
    | '/_authenticated/_app/ficha-tecnica'
    | '/_authenticated/_app/financeiro'
    | '/_authenticated/_app/fit-sessions'
    | '/_authenticated/_app/fornecedores'
    | '/_authenticated/_app/fpa'
    | '/_authenticated/_app/geo-sales'
    | '/_authenticated/_app/grade-needs'
    | '/_authenticated/_app/influencer-roi'
    | '/_authenticated/_app/influencers'
    | '/_authenticated/_app/inspecoes'
    | '/_authenticated/_app/intel-hub'
    | '/_authenticated/_app/intelligence'
    | '/_authenticated/_app/lotes'
    | '/_authenticated/_app/margem'
    | '/_authenticated/_app/marketing'
    | '/_authenticated/_app/marketing-envios'
    | '/_authenticated/_app/materiais'
    | '/_authenticated/_app/mobile'
    | '/_authenticated/_app/movimentacoes'
    | '/_authenticated/_app/omnichannel'
    | '/_authenticated/_app/onde-esta'
    | '/_authenticated/_app/pcp'
    | '/_authenticated/_app/pcp-kanban'
    | '/_authenticated/_app/pcp-stages'
    | '/_authenticated/_app/pedidos-compra'
    | '/_authenticated/_app/pilots'
    | '/_authenticated/_app/product-score'
    | '/_authenticated/_app/product-success'
    | '/_authenticated/_app/produtos'
    | '/_authenticated/_app/profitability'
    | '/_authenticated/_app/prototipos'
    | '/_authenticated/_app/quality'
    | '/_authenticated/_app/replenishment'
    | '/_authenticated/_app/representantes'
    | '/_authenticated/_app/sales-performance'
    | '/_authenticated/_app/security-center'
    | '/_authenticated/_app/showroom'
    | '/_authenticated/_app/sourcing'
    | '/_authenticated/_app/stock-health'
    | '/_authenticated/_app/supplier-score'
    | '/_authenticated/_app/sustentabilidade'
    | '/_authenticated/_app/sustentabilidade-360'
    | '/_authenticated/_app/target-costing'
    | '/_authenticated/_app/terceirizados'
    | '/_authenticated/_app/trends'
    | '/_authenticated/_app/twin-factory'
    | '/_authenticated/_app/use-ai'
    | '/_authenticated/_app/variantes'
    | '/_authenticated/_app/war-room-producao'
    | '/portal/fornecedor/$token'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/producao-do-dia/$stage'
    | '/_authenticated/_app/war-room-colecao/$id'
    | '/api/public/agents/run-due'
    | '/api/public/erp-sync/$publicId'
    | '/api/public/supplier-portal/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  DppIdRoute: typeof DppIdRoute
  PortalFornecedorTokenRoute: typeof PortalFornecedorTokenRoute
  ApiPublicAgentsRunDueRoute: typeof ApiPublicAgentsRunDueRoute
  ApiPublicErpSyncPublicIdRoute: typeof ApiPublicErpSyncPublicIdRoute
  ApiPublicSupplierPortalTokenRoute: typeof ApiPublicSupplierPortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp/$id': {
      id: '/dpp/$id'
      path: '/dpp/$id'
      fullPath: '/dpp/$id'
      preLoaderRoute: typeof DppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/portal/fornecedor/$token': {
      id: '/portal/fornecedor/$token'
      path: '/portal/fornecedor/$token'
      fullPath: '/portal/fornecedor/$token'
      preLoaderRoute: typeof PortalFornecedorTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/war-room-producao': {
      id: '/_authenticated/_app/war-room-producao'
      path: '/war-room-producao'
      fullPath: '/war-room-producao'
      preLoaderRoute: typeof AuthenticatedAppWarRoomProducaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/variantes': {
      id: '/_authenticated/_app/variantes'
      path: '/variantes'
      fullPath: '/variantes'
      preLoaderRoute: typeof AuthenticatedAppVariantesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/use-ai': {
      id: '/_authenticated/_app/use-ai'
      path: '/use-ai'
      fullPath: '/use-ai'
      preLoaderRoute: typeof AuthenticatedAppUseAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/twin-factory': {
      id: '/_authenticated/_app/twin-factory'
      path: '/twin-factory'
      fullPath: '/twin-factory'
      preLoaderRoute: typeof AuthenticatedAppTwinFactoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/trends': {
      id: '/_authenticated/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedAppTrendsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/terceirizados': {
      id: '/_authenticated/_app/terceirizados'
      path: '/terceirizados'
      fullPath: '/terceirizados'
      preLoaderRoute: typeof AuthenticatedAppTerceirizadosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/target-costing': {
      id: '/_authenticated/_app/target-costing'
      path: '/target-costing'
      fullPath: '/target-costing'
      preLoaderRoute: typeof AuthenticatedAppTargetCostingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sustentabilidade-360': {
      id: '/_authenticated/_app/sustentabilidade-360'
      path: '/sustentabilidade-360'
      fullPath: '/sustentabilidade-360'
      preLoaderRoute: typeof AuthenticatedAppSustentabilidade360RouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sustentabilidade': {
      id: '/_authenticated/_app/sustentabilidade'
      path: '/sustentabilidade'
      fullPath: '/sustentabilidade'
      preLoaderRoute: typeof AuthenticatedAppSustentabilidadeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/supplier-score': {
      id: '/_authenticated/_app/supplier-score'
      path: '/supplier-score'
      fullPath: '/supplier-score'
      preLoaderRoute: typeof AuthenticatedAppSupplierScoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/stock-health': {
      id: '/_authenticated/_app/stock-health'
      path: '/stock-health'
      fullPath: '/stock-health'
      preLoaderRoute: typeof AuthenticatedAppStockHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sourcing': {
      id: '/_authenticated/_app/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof AuthenticatedAppSourcingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/showroom': {
      id: '/_authenticated/_app/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof AuthenticatedAppShowroomRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/security-center': {
      id: '/_authenticated/_app/security-center'
      path: '/security-center'
      fullPath: '/security-center'
      preLoaderRoute: typeof AuthenticatedAppSecurityCenterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sales-performance': {
      id: '/_authenticated/_app/sales-performance'
      path: '/sales-performance'
      fullPath: '/sales-performance'
      preLoaderRoute: typeof AuthenticatedAppSalesPerformanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/representantes': {
      id: '/_authenticated/_app/representantes'
      path: '/representantes'
      fullPath: '/representantes'
      preLoaderRoute: typeof AuthenticatedAppRepresentantesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/replenishment': {
      id: '/_authenticated/_app/replenishment'
      path: '/replenishment'
      fullPath: '/replenishment'
      preLoaderRoute: typeof AuthenticatedAppReplenishmentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/quality': {
      id: '/_authenticated/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedAppQualityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/prototipos': {
      id: '/_authenticated/_app/prototipos'
      path: '/prototipos'
      fullPath: '/prototipos'
      preLoaderRoute: typeof AuthenticatedAppPrototiposRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/profitability': {
      id: '/_authenticated/_app/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof AuthenticatedAppProfitabilityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/produtos': {
      id: '/_authenticated/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedAppProdutosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/product-success': {
      id: '/_authenticated/_app/product-success'
      path: '/product-success'
      fullPath: '/product-success'
      preLoaderRoute: typeof AuthenticatedAppProductSuccessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/product-score': {
      id: '/_authenticated/_app/product-score'
      path: '/product-score'
      fullPath: '/product-score'
      preLoaderRoute: typeof AuthenticatedAppProductScoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pilots': {
      id: '/_authenticated/_app/pilots'
      path: '/pilots'
      fullPath: '/pilots'
      preLoaderRoute: typeof AuthenticatedAppPilotsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pedidos-compra': {
      id: '/_authenticated/_app/pedidos-compra'
      path: '/pedidos-compra'
      fullPath: '/pedidos-compra'
      preLoaderRoute: typeof AuthenticatedAppPedidosCompraRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pcp-stages': {
      id: '/_authenticated/_app/pcp-stages'
      path: '/pcp-stages'
      fullPath: '/pcp-stages'
      preLoaderRoute: typeof AuthenticatedAppPcpStagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pcp-kanban': {
      id: '/_authenticated/_app/pcp-kanban'
      path: '/pcp-kanban'
      fullPath: '/pcp-kanban'
      preLoaderRoute: typeof AuthenticatedAppPcpKanbanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/pcp': {
      id: '/_authenticated/_app/pcp'
      path: '/pcp'
      fullPath: '/pcp'
      preLoaderRoute: typeof AuthenticatedAppPcpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/onde-esta': {
      id: '/_authenticated/_app/onde-esta'
      path: '/onde-esta'
      fullPath: '/onde-esta'
      preLoaderRoute: typeof AuthenticatedAppOndeEstaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/omnichannel': {
      id: '/_authenticated/_app/omnichannel'
      path: '/omnichannel'
      fullPath: '/omnichannel'
      preLoaderRoute: typeof AuthenticatedAppOmnichannelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/movimentacoes': {
      id: '/_authenticated/_app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedAppMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/mobile': {
      id: '/_authenticated/_app/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthenticatedAppMobileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/materiais': {
      id: '/_authenticated/_app/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedAppMateriaisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/marketing-envios': {
      id: '/_authenticated/_app/marketing-envios'
      path: '/marketing-envios'
      fullPath: '/marketing-envios'
      preLoaderRoute: typeof AuthenticatedAppMarketingEnviosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/marketing': {
      id: '/_authenticated/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedAppMarketingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/margem': {
      id: '/_authenticated/_app/margem'
      path: '/margem'
      fullPath: '/margem'
      preLoaderRoute: typeof AuthenticatedAppMargemRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/lotes': {
      id: '/_authenticated/_app/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AuthenticatedAppLotesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/intelligence': {
      id: '/_authenticated/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedAppIntelligenceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/intel-hub': {
      id: '/_authenticated/_app/intel-hub'
      path: '/intel-hub'
      fullPath: '/intel-hub'
      preLoaderRoute: typeof AuthenticatedAppIntelHubRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/inspecoes': {
      id: '/_authenticated/_app/inspecoes'
      path: '/inspecoes'
      fullPath: '/inspecoes'
      preLoaderRoute: typeof AuthenticatedAppInspecoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/influencers': {
      id: '/_authenticated/_app/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof AuthenticatedAppInfluencersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/influencer-roi': {
      id: '/_authenticated/_app/influencer-roi'
      path: '/influencer-roi'
      fullPath: '/influencer-roi'
      preLoaderRoute: typeof AuthenticatedAppInfluencerRoiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/grade-needs': {
      id: '/_authenticated/_app/grade-needs'
      path: '/grade-needs'
      fullPath: '/grade-needs'
      preLoaderRoute: typeof AuthenticatedAppGradeNeedsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/geo-sales': {
      id: '/_authenticated/_app/geo-sales'
      path: '/geo-sales'
      fullPath: '/geo-sales'
      preLoaderRoute: typeof AuthenticatedAppGeoSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fpa': {
      id: '/_authenticated/_app/fpa'
      path: '/fpa'
      fullPath: '/fpa'
      preLoaderRoute: typeof AuthenticatedAppFpaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fornecedores': {
      id: '/_authenticated/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedAppFornecedoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fit-sessions': {
      id: '/_authenticated/_app/fit-sessions'
      path: '/fit-sessions'
      fullPath: '/fit-sessions'
      preLoaderRoute: typeof AuthenticatedAppFitSessionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/financeiro': {
      id: '/_authenticated/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/ficha-tecnica': {
      id: '/_authenticated/_app/ficha-tecnica'
      path: '/ficha-tecnica'
      fullPath: '/ficha-tecnica'
      preLoaderRoute: typeof AuthenticatedAppFichaTecnicaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fashion-gpt': {
      id: '/_authenticated/_app/fashion-gpt'
      path: '/fashion-gpt'
      fullPath: '/fashion-gpt'
      preLoaderRoute: typeof AuthenticatedAppFashionGptRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/fashion-calendar': {
      id: '/_authenticated/_app/fashion-calendar'
      path: '/fashion-calendar'
      fullPath: '/fashion-calendar'
      preLoaderRoute: typeof AuthenticatedAppFashionCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/erp-integration': {
      id: '/_authenticated/_app/erp-integration'
      path: '/erp-integration'
      fullPath: '/erp-integration'
      preLoaderRoute: typeof AuthenticatedAppErpIntegrationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/equipe': {
      id: '/_authenticated/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedAppEquipeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dpp': {
      id: '/_authenticated/_app/dpp'
      path: '/dpp'
      fullPath: '/dpp'
      preLoaderRoute: typeof AuthenticatedAppDppRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dev-kanban': {
      id: '/_authenticated/_app/dev-kanban'
      path: '/dev-kanban'
      fullPath: '/dev-kanban'
      preLoaderRoute: typeof AuthenticatedAppDevKanbanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/designer-workspace': {
      id: '/_authenticated/_app/designer-workspace'
      path: '/designer-workspace'
      fullPath: '/designer-workspace'
      preLoaderRoute: typeof AuthenticatedAppDesignerWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/data-lake': {
      id: '/_authenticated/_app/data-lake'
      path: '/data-lake'
      fullPath: '/data-lake'
      preLoaderRoute: typeof AuthenticatedAppDataLakeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/control-tower': {
      id: '/_authenticated/_app/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof AuthenticatedAppControlTowerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/compras': {
      id: '/_authenticated/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedAppComprasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/comercial': {
      id: '/_authenticated/_app/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedAppComercialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/colecoes': {
      id: '/_authenticated/_app/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof AuthenticatedAppColecoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/colecao-360': {
      id: '/_authenticated/_app/colecao-360'
      path: '/colecao-360'
      fullPath: '/colecao-360'
      preLoaderRoute: typeof AuthenticatedAppColecao360RouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/closed-loop': {
      id: '/_authenticated/_app/closed-loop'
      path: '/closed-loop'
      fullPath: '/closed-loop'
      preLoaderRoute: typeof AuthenticatedAppClosedLoopRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/clientes': {
      id: '/_authenticated/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/centro-de-corte': {
      id: '/_authenticated/_app/centro-de-corte'
      path: '/centro-de-corte'
      fullPath: '/centro-de-corte'
      preLoaderRoute: typeof AuthenticatedAppCentroDeCorteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cashflow': {
      id: '/_authenticated/_app/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AuthenticatedAppCashflowRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/capacity': {
      id: '/_authenticated/_app/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof AuthenticatedAppCapacityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/campaigns': {
      id: '/_authenticated/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cadeia-360': {
      id: '/_authenticated/_app/cadeia-360'
      path: '/cadeia-360'
      fullPath: '/cadeia-360'
      preLoaderRoute: typeof AuthenticatedAppCadeia360RouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cad': {
      id: '/_authenticated/_app/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AuthenticatedAppCadRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/bi': {
      id: '/_authenticated/_app/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedAppBiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/audit': {
      id: '/_authenticated/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/attribution': {
      id: '/_authenticated/_app/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof AuthenticatedAppAttributionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/approvals': {
      id: '/_authenticated/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedAppApprovalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/almoxarifado': {
      id: '/_authenticated/_app/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AuthenticatedAppAlmoxarifadoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/supplier-portal/$token': {
      id: '/api/public/supplier-portal/$token'
      path: '/api/public/supplier-portal/$token'
      fullPath: '/api/public/supplier-portal/$token'
      preLoaderRoute: typeof ApiPublicSupplierPortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erp-sync/$publicId': {
      id: '/api/public/erp-sync/$publicId'
      path: '/api/public/erp-sync/$publicId'
      fullPath: '/api/public/erp-sync/$publicId'
      preLoaderRoute: typeof ApiPublicErpSyncPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/run-due': {
      id: '/api/public/agents/run-due'
      path: '/api/public/agents/run-due'
      fullPath: '/api/public/agents/run-due'
      preLoaderRoute: typeof ApiPublicAgentsRunDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/war-room-colecao/$id': {
      id: '/_authenticated/_app/war-room-colecao/$id'
      path: '/war-room-colecao/$id'
      fullPath: '/war-room-colecao/$id'
      preLoaderRoute: typeof AuthenticatedAppWarRoomColecaoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/producao-do-dia/$stage': {
      id: '/_authenticated/_app/producao-do-dia/$stage'
      path: '/producao-do-dia/$stage'
      fullPath: '/producao-do-dia/$stage'
      preLoaderRoute: typeof AuthenticatedAppProducaoDoDiaStageRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlmoxarifadoRoute: typeof AuthenticatedAppAlmoxarifadoRoute
  AuthenticatedAppApprovalsRoute: typeof AuthenticatedAppApprovalsRoute
  AuthenticatedAppAttributionRoute: typeof AuthenticatedAppAttributionRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppBiRoute: typeof AuthenticatedAppBiRoute
  AuthenticatedAppCadRoute: typeof AuthenticatedAppCadRoute
  AuthenticatedAppCadeia360Route: typeof AuthenticatedAppCadeia360Route
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppCapacityRoute: typeof AuthenticatedAppCapacityRoute
  AuthenticatedAppCashflowRoute: typeof AuthenticatedAppCashflowRoute
  AuthenticatedAppCentroDeCorteRoute: typeof AuthenticatedAppCentroDeCorteRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppClosedLoopRoute: typeof AuthenticatedAppClosedLoopRoute
  AuthenticatedAppColecao360Route: typeof AuthenticatedAppColecao360Route
  AuthenticatedAppColecoesRoute: typeof AuthenticatedAppColecoesRoute
  AuthenticatedAppComercialRoute: typeof AuthenticatedAppComercialRoute
  AuthenticatedAppComprasRoute: typeof AuthenticatedAppComprasRoute
  AuthenticatedAppControlTowerRoute: typeof AuthenticatedAppControlTowerRoute
  AuthenticatedAppDataLakeRoute: typeof AuthenticatedAppDataLakeRoute
  AuthenticatedAppDesignerWorkspaceRoute: typeof AuthenticatedAppDesignerWorkspaceRoute
  AuthenticatedAppDevKanbanRoute: typeof AuthenticatedAppDevKanbanRoute
  AuthenticatedAppDppRoute: typeof AuthenticatedAppDppRoute
  AuthenticatedAppEquipeRoute: typeof AuthenticatedAppEquipeRoute
  AuthenticatedAppErpIntegrationRoute: typeof AuthenticatedAppErpIntegrationRoute
  AuthenticatedAppFashionCalendarRoute: typeof AuthenticatedAppFashionCalendarRoute
  AuthenticatedAppFashionGptRoute: typeof AuthenticatedAppFashionGptRoute
  AuthenticatedAppFichaTecnicaRoute: typeof AuthenticatedAppFichaTecnicaRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppFitSessionsRoute: typeof AuthenticatedAppFitSessionsRoute
  AuthenticatedAppFornecedoresRoute: typeof AuthenticatedAppFornecedoresRoute
  AuthenticatedAppFpaRoute: typeof AuthenticatedAppFpaRoute
  AuthenticatedAppGeoSalesRoute: typeof AuthenticatedAppGeoSalesRoute
  AuthenticatedAppGradeNeedsRoute: typeof AuthenticatedAppGradeNeedsRoute
  AuthenticatedAppInfluencerRoiRoute: typeof AuthenticatedAppInfluencerRoiRoute
  AuthenticatedAppInfluencersRoute: typeof AuthenticatedAppInfluencersRoute
  AuthenticatedAppInspecoesRoute: typeof AuthenticatedAppInspecoesRoute
  AuthenticatedAppIntelHubRoute: typeof AuthenticatedAppIntelHubRoute
  AuthenticatedAppIntelligenceRoute: typeof AuthenticatedAppIntelligenceRoute
  AuthenticatedAppLotesRoute: typeof AuthenticatedAppLotesRoute
  AuthenticatedAppMargemRoute: typeof AuthenticatedAppMargemRoute
  AuthenticatedAppMarketingRoute: typeof AuthenticatedAppMarketingRoute
  AuthenticatedAppMarketingEnviosRoute: typeof AuthenticatedAppMarketingEnviosRoute
  AuthenticatedAppMateriaisRoute: typeof AuthenticatedAppMateriaisRoute
  AuthenticatedAppMobileRoute: typeof AuthenticatedAppMobileRoute
  AuthenticatedAppMovimentacoesRoute: typeof AuthenticatedAppMovimentacoesRoute
  AuthenticatedAppOmnichannelRoute: typeof AuthenticatedAppOmnichannelRoute
  AuthenticatedAppOndeEstaRoute: typeof AuthenticatedAppOndeEstaRoute
  AuthenticatedAppPcpRoute: typeof AuthenticatedAppPcpRoute
  AuthenticatedAppPcpKanbanRoute: typeof AuthenticatedAppPcpKanbanRoute
  AuthenticatedAppPcpStagesRoute: typeof AuthenticatedAppPcpStagesRoute
  AuthenticatedAppPedidosCompraRoute: typeof AuthenticatedAppPedidosCompraRoute
  AuthenticatedAppPilotsRoute: typeof AuthenticatedAppPilotsRoute
  AuthenticatedAppProductScoreRoute: typeof AuthenticatedAppProductScoreRoute
  AuthenticatedAppProductSuccessRoute: typeof AuthenticatedAppProductSuccessRoute
  AuthenticatedAppProdutosRoute: typeof AuthenticatedAppProdutosRoute
  AuthenticatedAppProfitabilityRoute: typeof AuthenticatedAppProfitabilityRoute
  AuthenticatedAppPrototiposRoute: typeof AuthenticatedAppPrototiposRoute
  AuthenticatedAppQualityRoute: typeof AuthenticatedAppQualityRoute
  AuthenticatedAppReplenishmentRoute: typeof AuthenticatedAppReplenishmentRoute
  AuthenticatedAppRepresentantesRoute: typeof AuthenticatedAppRepresentantesRoute
  AuthenticatedAppSalesPerformanceRoute: typeof AuthenticatedAppSalesPerformanceRoute
  AuthenticatedAppSecurityCenterRoute: typeof AuthenticatedAppSecurityCenterRoute
  AuthenticatedAppShowroomRoute: typeof AuthenticatedAppShowroomRoute
  AuthenticatedAppSourcingRoute: typeof AuthenticatedAppSourcingRoute
  AuthenticatedAppStockHealthRoute: typeof AuthenticatedAppStockHealthRoute
  AuthenticatedAppSupplierScoreRoute: typeof AuthenticatedAppSupplierScoreRoute
  AuthenticatedAppSustentabilidadeRoute: typeof AuthenticatedAppSustentabilidadeRoute
  AuthenticatedAppSustentabilidade360Route: typeof AuthenticatedAppSustentabilidade360Route
  AuthenticatedAppTargetCostingRoute: typeof AuthenticatedAppTargetCostingRoute
  AuthenticatedAppTerceirizadosRoute: typeof AuthenticatedAppTerceirizadosRoute
  AuthenticatedAppTrendsRoute: typeof AuthenticatedAppTrendsRoute
  AuthenticatedAppTwinFactoryRoute: typeof AuthenticatedAppTwinFactoryRoute
  AuthenticatedAppUseAiRoute: typeof AuthenticatedAppUseAiRoute
  AuthenticatedAppVariantesRoute: typeof AuthenticatedAppVariantesRoute
  AuthenticatedAppWarRoomProducaoRoute: typeof AuthenticatedAppWarRoomProducaoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppProducaoDoDiaStageRoute: typeof AuthenticatedAppProducaoDoDiaStageRoute
  AuthenticatedAppWarRoomColecaoIdRoute: typeof AuthenticatedAppWarRoomColecaoIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlmoxarifadoRoute: AuthenticatedAppAlmoxarifadoRoute,
  AuthenticatedAppApprovalsRoute: AuthenticatedAppApprovalsRoute,
  AuthenticatedAppAttributionRoute: AuthenticatedAppAttributionRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppBiRoute: AuthenticatedAppBiRoute,
  AuthenticatedAppCadRoute: AuthenticatedAppCadRoute,
  AuthenticatedAppCadeia360Route: AuthenticatedAppCadeia360Route,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppCapacityRoute: AuthenticatedAppCapacityRoute,
  AuthenticatedAppCashflowRoute: AuthenticatedAppCashflowRoute,
  AuthenticatedAppCentroDeCorteRoute: AuthenticatedAppCentroDeCorteRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppClosedLoopRoute: AuthenticatedAppClosedLoopRoute,
  AuthenticatedAppColecao360Route: AuthenticatedAppColecao360Route,
  AuthenticatedAppColecoesRoute: AuthenticatedAppColecoesRoute,
  AuthenticatedAppComercialRoute: AuthenticatedAppComercialRoute,
  AuthenticatedAppComprasRoute: AuthenticatedAppComprasRoute,
  AuthenticatedAppControlTowerRoute: AuthenticatedAppControlTowerRoute,
  AuthenticatedAppDataLakeRoute: AuthenticatedAppDataLakeRoute,
  AuthenticatedAppDesignerWorkspaceRoute:
    AuthenticatedAppDesignerWorkspaceRoute,
  AuthenticatedAppDevKanbanRoute: AuthenticatedAppDevKanbanRoute,
  AuthenticatedAppDppRoute: AuthenticatedAppDppRoute,
  AuthenticatedAppEquipeRoute: AuthenticatedAppEquipeRoute,
  AuthenticatedAppErpIntegrationRoute: AuthenticatedAppErpIntegrationRoute,
  AuthenticatedAppFashionCalendarRoute: AuthenticatedAppFashionCalendarRoute,
  AuthenticatedAppFashionGptRoute: AuthenticatedAppFashionGptRoute,
  AuthenticatedAppFichaTecnicaRoute: AuthenticatedAppFichaTecnicaRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppFitSessionsRoute: AuthenticatedAppFitSessionsRoute,
  AuthenticatedAppFornecedoresRoute: AuthenticatedAppFornecedoresRoute,
  AuthenticatedAppFpaRoute: AuthenticatedAppFpaRoute,
  AuthenticatedAppGeoSalesRoute: AuthenticatedAppGeoSalesRoute,
  AuthenticatedAppGradeNeedsRoute: AuthenticatedAppGradeNeedsRoute,
  AuthenticatedAppInfluencerRoiRoute: AuthenticatedAppInfluencerRoiRoute,
  AuthenticatedAppInfluencersRoute: AuthenticatedAppInfluencersRoute,
  AuthenticatedAppInspecoesRoute: AuthenticatedAppInspecoesRoute,
  AuthenticatedAppIntelHubRoute: AuthenticatedAppIntelHubRoute,
  AuthenticatedAppIntelligenceRoute: AuthenticatedAppIntelligenceRoute,
  AuthenticatedAppLotesRoute: AuthenticatedAppLotesRoute,
  AuthenticatedAppMargemRoute: AuthenticatedAppMargemRoute,
  AuthenticatedAppMarketingRoute: AuthenticatedAppMarketingRoute,
  AuthenticatedAppMarketingEnviosRoute: AuthenticatedAppMarketingEnviosRoute,
  AuthenticatedAppMateriaisRoute: AuthenticatedAppMateriaisRoute,
  AuthenticatedAppMobileRoute: AuthenticatedAppMobileRoute,
  AuthenticatedAppMovimentacoesRoute: AuthenticatedAppMovimentacoesRoute,
  AuthenticatedAppOmnichannelRoute: AuthenticatedAppOmnichannelRoute,
  AuthenticatedAppOndeEstaRoute: AuthenticatedAppOndeEstaRoute,
  AuthenticatedAppPcpRoute: AuthenticatedAppPcpRoute,
  AuthenticatedAppPcpKanbanRoute: AuthenticatedAppPcpKanbanRoute,
  AuthenticatedAppPcpStagesRoute: AuthenticatedAppPcpStagesRoute,
  AuthenticatedAppPedidosCompraRoute: AuthenticatedAppPedidosCompraRoute,
  AuthenticatedAppPilotsRoute: AuthenticatedAppPilotsRoute,
  AuthenticatedAppProductScoreRoute: AuthenticatedAppProductScoreRoute,
  AuthenticatedAppProductSuccessRoute: AuthenticatedAppProductSuccessRoute,
  AuthenticatedAppProdutosRoute: AuthenticatedAppProdutosRoute,
  AuthenticatedAppProfitabilityRoute: AuthenticatedAppProfitabilityRoute,
  AuthenticatedAppPrototiposRoute: AuthenticatedAppPrototiposRoute,
  AuthenticatedAppQualityRoute: AuthenticatedAppQualityRoute,
  AuthenticatedAppReplenishmentRoute: AuthenticatedAppReplenishmentRoute,
  AuthenticatedAppRepresentantesRoute: AuthenticatedAppRepresentantesRoute,
  AuthenticatedAppSalesPerformanceRoute: AuthenticatedAppSalesPerformanceRoute,
  AuthenticatedAppSecurityCenterRoute: AuthenticatedAppSecurityCenterRoute,
  AuthenticatedAppShowroomRoute: AuthenticatedAppShowroomRoute,
  AuthenticatedAppSourcingRoute: AuthenticatedAppSourcingRoute,
  AuthenticatedAppStockHealthRoute: AuthenticatedAppStockHealthRoute,
  AuthenticatedAppSupplierScoreRoute: AuthenticatedAppSupplierScoreRoute,
  AuthenticatedAppSustentabilidadeRoute: AuthenticatedAppSustentabilidadeRoute,
  AuthenticatedAppSustentabilidade360Route:
    AuthenticatedAppSustentabilidade360Route,
  AuthenticatedAppTargetCostingRoute: AuthenticatedAppTargetCostingRoute,
  AuthenticatedAppTerceirizadosRoute: AuthenticatedAppTerceirizadosRoute,
  AuthenticatedAppTrendsRoute: AuthenticatedAppTrendsRoute,
  AuthenticatedAppTwinFactoryRoute: AuthenticatedAppTwinFactoryRoute,
  AuthenticatedAppUseAiRoute: AuthenticatedAppUseAiRoute,
  AuthenticatedAppVariantesRoute: AuthenticatedAppVariantesRoute,
  AuthenticatedAppWarRoomProducaoRoute: AuthenticatedAppWarRoomProducaoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppProducaoDoDiaStageRoute:
    AuthenticatedAppProducaoDoDiaStageRoute,
  AuthenticatedAppWarRoomColecaoIdRoute: AuthenticatedAppWarRoomColecaoIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  DppIdRoute: DppIdRoute,
  PortalFornecedorTokenRoute: PortalFornecedorTokenRoute,
  ApiPublicAgentsRunDueRoute: ApiPublicAgentsRunDueRoute,
  ApiPublicErpSyncPublicIdRoute: ApiPublicErpSyncPublicIdRoute,
  ApiPublicSupplierPortalTokenRoute: ApiPublicSupplierPortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
